"""Extensible callback system for augmenting objects and tracking iterations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_callback.ipynb.

# %% ../nbs/10_callback.ipynb #3c5f0051
from __future__ import annotations

# %% auto #0
__all__ = ['Callback', 'run_cbs', 'EchoCB', 'CBs', 'PassCB', 'HasCallbacks', 'with_cbs', 'CollBack', 'trackback', 'process_']

# %% ../nbs/10_callback.ipynb #e1321115
import collections
import time
from contextlib import contextmanager
from functools import partial
from operator import attrgetter
from operator import length_hint
from typing import Any
from typing import Callable
from typing import Iterable
from typing import Iterator
from typing import Self
from typing import Sequence
from typing import Type
from typing import TypeVar

import fastcore.all as FC

# %% ../nbs/10_callback.ipynb #1cdc2e9e
from .basic import AD
from .basic import empty
from .basic import EmptyT
from .basic import is_listy
from .basic import Runner
from .basic import setattrs
from .basic import update_

# %% ../nbs/10_callback.ipynb #2ed7bc95
class Callback:
    "Base class of callbacks."
    order, cbs = 0, ()
    cbs: Sequence[Callback]  # if present, run callbacks in the list after running this callback

# %% ../nbs/10_callback.ipynb #0cfa8456
def run_cbs(cbs: Iterable[Callback], method_nm:str, ctx=None, *args, **kwargs):
    "Run `method_nm(ctx, ...)` of each callback in `cbs` in order."
    for cb in sorted(cbs, key=attrgetter('order')):
        if f := getattr(cb, method_nm, None): Runner(f)(ctx, *args, **kwargs)
        # Safely check for nested cbs - must be iterable but not string/bytes/method
        if is_listy(nested := getattr(cb, 'cbs', None)):
            run_cbs((x for x in nested if x != cb), method_nm, ctx, *args, **kwargs)

# %% ../nbs/10_callback.ipynb #4e40bfee
class EchoCB(Callback):
    "Print the arguments."
    def echo(self, ctx, *args, **kwargs): print(ctx, args, kwargs)
    def __getattr__(self, name): return partial(self.echo, name)

# %% ../nbs/10_callback.ipynb #9f1aa9d3
class CBs(Callback):
    "Store callables that can be called as callbacks."
    def __init__(self, **kwargs): setattrs(self, kwargs)

# %% ../nbs/10_callback.ipynb #80dd6d78
class PassCB(Callback):
    "A callback that does nothing."
    def noop(self, *args, **kwargs): pass
    def __getattr__(self, name): return self.noop

# %% ../nbs/10_callback.ipynb #5ab5c2c0
class HasCallbacks:
    "Base for classes that can be augmented with callbacks."
    cbs: list[Callback]
    cbs_names: tuple[str,...] = ()  # this callbacks becomes self methods if a subclass overrides them

    def __new__(cls, *args, **kwargs):
        self = super().__new__(cls)
        self.cbs = []#PassCB()]
        return self

    def __init__(self, cbs:Sequence[Callback]=()): self.cbs = list(cbs)

    def with_cbs(self, cbs:Sequence[Callback], extend=False):
        if extend: self.cbs.extend(cbs)
        else: self.cbs = list(cbs)
        return self
    
    @contextmanager
    def this_cbs(self, cbs:Sequence[Callback]):
        "Use temporary `cbs` in `with` block."
        for cb in cbs: self.cbs.append(cb)
        try: yield        
        finally:
            for cb in cbs: self.cbs.remove(cb)

    def __getattr__(self, name):
        "Run `name` as a callback if it's in `self.cbs_names`."
        if name in self.cbs_names: return partial(self.callback, name)
        raise AttributeError(name)

    def callback(self, method_nm, *args, **kwargs): run_cbs(self.cbs, method_nm, self, *args, **kwargs)

# %% ../nbs/10_callback.ipynb #d46aafcc
class with_cbs:
    "Decorator to add callbacks to a method."
    def __init__(self, nm:str|None=None): self.nm = nm
    def __call__(self, f):
        def _f(o, *args, **kwargs):
            nm = self.nm or f.__name__
            try:
                o.callback(f'before_{nm}')
                f(o, *args, **kwargs)
                o.callback(f'after_{nm}')
            except globals()[f'Cancel{nm.title()}Exception']: pass
            finally: o.callback(f'cleanup_{nm}')
        return _f

# %% ../nbs/10_callback.ipynb #d33dda80
def _get_total(total: int|None|Type[EmptyT], source) -> int|None:
    if total is empty:
        try: return len(source)
        except: return length_hint(source) or None
    if total is not None and (not isinstance(total, int) or total < 0): total = None
    return total

# %% ../nbs/10_callback.ipynb #25fb0683
class CollBack(HasCallbacks):
    "Track iterables and extend them with callbacks."

    cbs_names = ('before_iter', 'after_iter', 'on_iter', 'on_interrupt')

    n: int|None = None
    start_time: float|None = None
    active, interrupted = False, False
    item: Any = empty
    def __init__(self, 
            source: Iterable[Any] = (), 
            total: int|None|Type[EmptyT] = empty, 
            context: Any = empty,
            **kwargs):
        self._source, self._total = source, total
        self.total: int|None = _get_total(self._total, self._source)
        self.context = context
        super().__init__(**kwargs)

    @property
    def progress(self):
        if self.total: return None if self.n is None else min(1., round((self.n+1)/float(self.total), 4))
        return None

    @property
    def elapsed_time(self): return (time.time() - self.start_time) if self.start_time else None

    @property
    def state(self):
        return AD(update_(item=self.item, n=self.n, total=self.total, progress=self.progress, 
            context=self.context, 
            elapsed_time=self.elapsed_time, interrupted=self.interrupted or empty, empty_value=empty))

    @property
    def state_(self):
        return AD(update_(item=self.item, n=self.n, total=self.total, progress=self.progress, 
            context=self.context, 
            interrupted=self.interrupted or empty, empty_value=empty))

    def __repr__(self): return f'{self.__class__.__name__}#{self._source}, total={self._total}'

    def _start(self):
        self.total = _get_total(self._total, self._source)
        self.active, self.start_time, self.n = True, time.time(), None
        run_cbs(self.cbs, 'before_iter', self)

    def _stop(self):
        if self.total is None and self.n is not None: self.total = self.n + 1
        self.active, self.item = False, empty
        run_cbs(self.cbs, 'after_iter', self)
    
    def _interrupt(self): self.interrupted = True; run_cbs(self.cbs, 'on_interrupt', self)

    def __iter__(self) -> Iterator[Any]:
        if self._source is None: return
        try:
            self._start()
            for self.n, self.item in enumerate(self._source):
                if self.total is not None and self.n >= self.total: break
                yield self.item
                run_cbs(self.cbs, 'on_iter', self, self.item)
                if self.total is not None and self.n >= self.total-1: break
        except Exception as e: self._interrupt(); raise e
        finally: self._stop()

    def _trackback(self, cbs:Sequence[Callback]=()) -> Iterator[tuple[Any, Self]]:
        with self.this_cbs(cbs):
            for elem in self:
                yield elem, self

# %% ../nbs/10_callback.ipynb #7d257581
def trackback(
    source: Iterable[Any], 
    total: int|None|Type[EmptyT]=empty, 
    context: Any=empty, 
    cbs:Sequence[Callback]=()
) -> Iterator[tuple[Any, CollBack]]:
    return CollBack(source, total, context, cbs=cbs)._trackback()

# %% ../nbs/10_callback.ipynb #95262973
_T = TypeVar('_T')

def process_(
        iterable:Iterable[_T], /, 
        *cbs: Callback, 
        slc:slice|None=None, 
        pred:Callable[[_T], bool]|None=None, 
        context:Any=empty,
        **kwargs  # FuncCB kwargs
    ) -> tuple[Callback,...]:
    "Process a subset `slc` of `iterable` filtered by `pred` with callbacks from `cbs` and `FuncCB` `kwargs`"
    _cbs = FC.tuplify(cbs) + ((CBs(**kwargs),) if kwargs else ())
    items = FC.L(iterable)[slc or slice(None)].filter(pred)  # type: ignore
    collections.deque(CollBack(items, context=context,cbs=_cbs), maxlen=0)
    return _cbs  # type: ignore
