"""dialog provides message and dialog introspection, and import/export utilities for solveit dialogs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dialog.ipynb.

# %% auto #0
__all__ = ['Msg', 'is_exported', 'is_hidden', 'is_echo', 'is_header', 'clamp_note', 'MsgX', 'msgx', 'find_msgs_x', 'output2md',
           'strip_directives', 'strip_tags', 'mk_frontmatter', 'exportmsgs', 'get_section', 'section_map',
           'filter_msgs_v1', 'filter_msgs_v2', 'find_symbol_msg', 'importdlg', 'nb_path', 'dlg_module', 'dlg_export',
           'get_dialog_link', 'empty_dialog_nb', 'get_msg_id', 'get_output', 'format_output', 'split_md_blocks']

# %% ../nbs/01_dialog.ipynb #1e28a183
import re, json
from html import escape
from pathlib import Path
from typing import TypeAlias
from IPython import get_ipython
from mistletoe import Document
from mistletoe.block_token import CodeFence
from mistletoe.markdown_renderer import MarkdownRenderer
from nbdev.process import extract_directives
from fastcore.foundation import patch, adict, AttrDict as AD
from fastcore.meta import delegates
from dialoghelper.core import add_msg, read_msg, find_msgs, msg_idx, run_msg, toggle_header, ast_py, find_dname
from .dutil import in_dialog

# %% ../nbs/01_dialog.ipynb #68d5b75e
Msg: TypeAlias = AD

# %% ../nbs/01_dialog.ipynb #8ca984e4
_exports = {'exporti', 'exports', 'export'}
_hidden = {'hide'}
_echo = {'echo', 'echo:'}

# %% ../nbs/01_dialog.ipynb #4426db27
def is_exported(m:Msg) -> bool:
    "Is message exported with solveit metadata or nbdev directive?"
    return m.is_exported or (m.msg_type == 'code' and bool(
        extract_directives(AD(source=m.content), remove=False).keys() & _exports))

def is_hidden(m:Msg) -> bool:
    "Is message hidden by a nbdev directive (only for doc generation, not AI visibility)?"
    return m.msg_type == 'code' and bool(
        extract_directives(AD(source=m.content), remove=False).keys() & _hidden)

def is_echo(m:Msg) -> bool:
    "Does message have an echo directive that isn't false?"
    if m.msg_type != 'code': return False
    d = {k:v for k,v in extract_directives(AD(source=m.content), remove=False).items() if k in _echo}
    return bool(d) and all('false' not in v for v in d.values())

def is_header(m:Msg) -> bool:
    "Does note message content start by a markdown header?"
    return m.msg_type == 'note' and m.content.startswith('#')

# %% ../nbs/01_dialog.ipynb #f463651b
def clamp_note(
    c:str, # Markdown note content
    level:str|int='header' # Disclosure level: 'header', 'header+', 'header++', or int for max lines
) -> str:
    "Return a progressively disclosed excerpt of a markdown note."
    c = c.strip().splitlines()
    if c:
        if isinstance(level, int): return '\n'.join(c[:level])
        if level == 'header': return c[0] if c[0][0] == '#' else ''
        if level == 'header+':
            i, res = 0, c[0]
            if res[0] != '#': return ''
            while (i:=i+1) < len(c):
                if c[i]: return f"{res}\n{c[i]}"
            return res
        if level.startswith('header++'):
            header = c[0] if c[0][0] == '#' else ''
            if not header: return ''
            blocks = [b.strip() for b in '\n'.join(c[1:]).split('\n\n') if b.strip()]
            if blocks:
                first = blocks[0].splitlines()[0]
                if not first.startswith('#') and not first.startswith(('```', '~~~')):
                    return f"{header}\n{blocks[0]}"
            return header
    return ''

# %% ../nbs/01_dialog.ipynb #4a03c72d
class MsgX(Msg): ...

# %% ../nbs/01_dialog.ipynb #8347e9f5
def msgx(msg:adict) -> None:
    "Return `msg` cast to MsgX."
    msg.__class__ = MsgX
    return msg

# %% ../nbs/01_dialog.ipynb #88f12bd3
@patch(as_prop=True)
def exported_x(self:MsgX) -> bool: return is_exported(self)
@patch(as_prop=True)
def hidden_x(self:MsgX) -> bool: return is_hidden(self)
@patch(as_prop=True)
def echo_x(self:MsgX) -> bool: return is_echo(self)
@patch(as_prop=True)
def header_x(self:MsgX) -> bool: return is_header(self)

# %% ../nbs/01_dialog.ipynb #02d7356e
@delegates(find_msgs)
async def find_msgs_x(*args, **kwargs) -> list[MsgX]:
    "find_msgs returning MsgX instances."
    ms = await find_msgs(*args, **kwargs)
    for m in ms: m.__class__ = MsgX
    return ms

# %% ../nbs/01_dialog.ipynb #643a905d
_pmark = '**🤖Reply🤖**<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->\n'

# %% ../nbs/01_dialog.ipynb #d2685927
def _mk_tag(m, mtyp, ids):
    # parts = ([f'#{m.id}'] if ids else []) + [mtyp] + (['echo'] if echo else []) + (['skipped'] if m.skipped else []) + (['pinned'] if m.pinned else [])
    parts = ([f'#{m.id}'] if ids else []) + [mtyp]
    return ' '.join(parts)

# %% ../nbs/01_dialog.ipynb #d2bc045a
def output2md(c, langid='output'):
    return f'''```{langid}\n{c}\n```''' if c else ''

# %% ../nbs/01_dialog.ipynb #ff4409be
def strip_directives(c): return ('\n'.join(l for l in c.splitlines() if not l.startswith('#|'))).strip()

# %% ../nbs/01_dialog.ipynb #9ba03aa3
_striptag_pats = (
    re.compile(r'^#\|\W*\w+: \w+\W*$\n?', re.MULTILINE),
    re.compile(r'^<!-- \w+: \w+ -->\s*\n?', re.MULTILINE))

def strip_tags(c):
    for pat in _striptag_pats: c = pat.sub('', c)
    return c.strip()

# %% ../nbs/01_dialog.ipynb #24b7596b
def _xml_msg(m:MsgX, ids, output, hdr_clamp):
    mtyp = m.msg_type
    c, attrs = '', (f' id="{m.id}"' if ids else '') + f' type="{mtyp}"'
    match mtyp:
        case 'note':
            clamp = not m.exported_x and m.header_x
            c = escape(strip_tags(clamp_note(m.content, hdr_clamp) if clamp else m.content))
            if c: c = f'<content>{c}</content>'
        case 'code':
            src = escape(strip_directives(m.content))
            out = f'\n  <output>{escape(m.output)}</output>' if output and m.output else ''
            if src or out: c = f'\n  <source>{src}</source>{out}\n'
        case 'prompt':
            p = escape(strip_tags(strip_directives(m.content)))
            r = f'\n  <response>{escape(m.output)}</response>' if m.output else ''
            if p or r: c = f'<prompt>{p}</prompt>{r}'
        case 'raw':
            c = escape(strip_tags(strip_directives(m.content)))
            if c: c = f'<msg{attrs}><content>{c}</content></msg>'
    return f'<msg{attrs}>{c}</msg>' if c else ''

# %% ../nbs/01_dialog.ipynb #d183b554
def _md_msg(m, ids, output, hdr_clamp):
    mtyp, c = m.msg_type, None
    match mtyp:
        case 'note':
            clamp = not m.exported_x and m.header_x
            c = strip_tags(clamp_note(m.content, hdr_clamp) if clamp else m.content)
        case 'code':
            c = f'```python\n{strip_directives(m.content)}\n```'
            if output and m.output: c += f'\n{output2md(m.output)}'
        case 'prompt':
            c = strip_tags(strip_directives(m.content))
            if output and m.output: c += f'\n{output2md(m.output, 'response')}'
        case 'raw': c = strip_tags(strip_directives(m.content))
    return f'<!-- {_mk_tag(m, mtyp, ids)} -->\n{c}\n' if c else ''

# %% ../nbs/01_dialog.ipynb #39d5c5d5
def _json_msg(m, expd, echo, ids, output, hdr_clamp):
    mtyp = m.msg_type
    d = dict(type=mtyp)
    if ids: d['id'] = m.id
    match mtyp:
        case 'note':
            clamp = not m.exported_x and m.header_x
            d['content'] = strip_tags(clamp_note(m.content, hdr_clamp) if clamp else m.content)
        case 'code':
            d['source'] = strip_directives(m.content)
            if output and m.output: d['output'] = m.output
        case 'prompt':
            d['prompt'] = strip_tags(strip_directives(m.content))
            d['response'] = m.output
        case 'raw': d['content'] = strip_tags(strip_directives(m.content))
    return d

# %% ../nbs/01_dialog.ipynb #1fe5afdb
_convs = dict(
    xml="msg elements have id and type attributes; source/output are child elements of code msgs; prompt/response are child elements of prompt msgs",
    json="msgs is a list of objects with type and id fields; code objects have source and output fields; prompt objects have prompt and response fields; others have content",
    md="<!-- #<msg_id> <msg_type> --> precedes each block; ```output blocks contain cell output; ```response blocks contain model response")

# %% ../nbs/01_dialog.ipynb #c02cd206
def mk_frontmatter(path='', description='', n_msgs=0, n_exported=0, fmt='xml'):
    from datetime import datetime, timezone
    return ("---\n"
"digest: solveit-dialog\n"
f"path: {path}\n"
f"exported_at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
f"description: {description!r}\n"
f"stats: {{total: {n_msgs}, exported: {n_exported}}}\n"
f"conventions: '{_convs[fmt]}'\n"
"---\n"
)

# %% ../nbs/01_dialog.ipynb #37710188
def exportmsgs(
    msgs:list[Msg],
    hdr_clamp='header+',  # header level
    output=True,  # include code messages output
    ids=True,  # include message ids in cell comments
    frontmatter:dict=None,  # if present, call `mk_frontmatter` with this dict as args
    fmt='xml',  # 'xml'|'md'|'json'
):
    "Export messages as a digest for AI consumption"
    fn = {'xml': _xml_msg, 'md': _md_msg, 'json': _json_msg}[fmt]
    parts = [p for m in msgs if (p := fn(m, ids, output, hdr_clamp))]
    if fmt == 'json': res = json.dumps({'msgs': parts}, indent=2)
    else:
        body = '\n'.join(parts)
        res = f'<digest>\n{body}\n</digest>' if fmt=='xml' else body
    if frontmatter:
        frontmatter.update(n_exported=len(parts))
        fm = mk_frontmatter(**frontmatter)
    return f"{fm}\n{res}" if frontmatter else res

# %% ../nbs/01_dialog.ipynb #7800f21f
_meta_fns = dict(exported=is_exported, echo=is_echo, header=is_header, hidden=is_hidden)

# %% ../nbs/01_dialog.ipynb #187cb632
async def get_section(heading:str, msgs:list[MsgX]=None, dname='') -> list[MsgX]:
    "Return messages in section whose header matches heading"
    if not msgs: return await find_msgs_x(header_section=heading, include_skipped=True, dname=dname)
    lvl = len(re.match(r'^(#+)', heading)[1])
    for i,m in enumerate(msgs):
        if m.msg_type != 'note' or not m.content.startswith(heading): continue
        res = [m]
        for m2 in msgs[i+1:]:
            hs = re.match(r'^(#+)', m2.content) if m2.msg_type == 'note' else None
            if hs and len(hs[1]) <= lvl: break
            res.append(m2)
        return res
    return []

# %% ../nbs/01_dialog.ipynb #c1f52e60
def _parse_terms(v):
    terms = ([v] if isinstance(v, str) else v) or []
    return [t for t in terms if not t.startswith('!')], [t[1:] for t in terms if t.startswith('!')]

# %% ../nbs/01_dialog.ipynb #67824193
def _content_match(m, pat, use_case, use_regex):
    flags = (re.DOTALL|re.MULTILINE)|(0 if use_case else re.IGNORECASE)
    return bool(re.search(pat, m.content, flags) if use_regex else (pat in m.content if use_case else pat.lower() in m.content.lower()))

# %% ../nbs/01_dialog.ipynb #00ff0767
def _header_level(m):
    if m.msg_type != 'note' or not m.content.startswith('#'): return 0
    return len(re.match(r'^(#+)', m.content)[1])


# %% ../nbs/01_dialog.ipynb #56979fd2
def section_map(msgs):
    "Return dict mapping full header line -> list of msg ids in that section (inclusive of header)"
    res, cur_hdrs = {}, []
    for m in msgs:
        lvl = _header_level(m)
        if lvl:
            cur_hdrs = [(l,h) for l,h in cur_hdrs if l < lvl]
            hdr = re.match(r'^(#+[^\n]*)', m.content)[1]
            cur_hdrs.append((lvl, hdr))
            for _,h in cur_hdrs: res.setdefault(h, []).append(m.id)
        else:
            for _,h in cur_hdrs: res.setdefault(h, []).append(m.id)
    return res

# %% ../nbs/01_dialog.ipynb #16a9f89d
def _resolve_sections(msgs, patterns):
    "Return set of msg ids matching any of the section patterns (supports regex via section_map)"
    sm = section_map(msgs)
    ids = set()
    for p in patterns:
        for k, v in sm.items():
            if re.fullmatch(p, k, re.IGNORECASE): ids |= set(v)
    return ids

# %% ../nbs/01_dialog.ipynb #073fd07f
async def filter_msgs_v1(
    msgs:list[Msg]=None,
    ids:str|list=None,
    section:str|list=None,
    msg_type:str|list=None,
    metadata:str|list=None,
    re_pattern:str='',
    use_case:bool=False,
    use_regex:bool=True,
    dname:str='',
) -> list[MsgX]:
    "Filter messages with union semantics and ! negation; result in dialog order."
    if not any([ids, section, msg_type, metadata, re_pattern]): return []
    msgs = msgs or await find_msgs_x(include_skipped=True, dname=dname)
    ids_l = ([ids] if isinstance(ids, str) else ids) or []
    sec_pos, sec_neg = _parse_terms(section)
    mt_pos, mt_neg = _parse_terms(msg_type)
    md_pos, md_neg = _parse_terms(metadata)
    pat_pos, pat_neg = (re_pattern[1:], True) if re_pattern.startswith('!') else (re_pattern, False)
    has_pos = any([ids_l, sec_pos, mt_pos, md_pos, (pat_pos and not pat_neg)])
    pos = set(ids_l)
    pos |= _resolve_sections(msgs, sec_pos)
    if mt_pos: pos |= {m.id for m in msgs if m.msg_type in mt_pos}
    if md_pos: pos |= {m.id for m in msgs if any(_meta_fns[k](m) for k in md_pos)}
    if pat_pos and not pat_neg: pos |= {m.id for m in msgs if _content_match(m, pat_pos, use_case, use_regex)}
    neg = set()
    neg |= _resolve_sections(msgs, sec_neg)
    if mt_neg: neg |= {m.id for m in msgs if m.msg_type in mt_neg}
    if md_neg: neg |= {m.id for m in msgs if any(_meta_fns[k](m) for k in md_neg)}
    if pat_neg: neg |= {m.id for m in msgs if _content_match(m, pat_pos, use_case, use_regex)}
    base = pos if has_pos else {m.id for m in msgs}
    return [m for m in msgs if m.id in base - neg]

# %% ../nbs/01_dialog.ipynb #9899a2d5
def _scope_msgs(msgs, ids, section):
    "Narrow msgs to those matching ids and/or section patterns."
    if ids is None and not section: return msgs
    scoped = set()
    if ids is not None: scoped |= {ids} if isinstance(ids, str) else set(ids)
    if section:
        secs = [section] if isinstance(section, str) else section
        scoped |= _resolve_sections(msgs, secs)
    return [m for m in msgs if m.id in scoped]

# %% ../nbs/01_dialog.ipynb #db9f095e
def _filter_pos_neg(msgs, msg_type=None, metadata=None, re_pattern='', use_case=False, use_regex=True):
    "Apply union+negation filter to msgs. If no positive terms, return msgs as-is."
    mt_pos, mt_neg = _parse_terms(msg_type)
    md_pos, md_neg = _parse_terms(metadata)
    pat_pos, pat_neg = (re_pattern[1:], True) if re_pattern.startswith('!') else (re_pattern, False)
    has_pos = any([mt_pos, md_pos, pat_pos and not pat_neg])
    if not has_pos and not any([mt_neg, md_neg, pat_neg]): return msgs
    pos = set()
    if mt_pos: pos |= {m.id for m in msgs if m.msg_type in mt_pos}
    if md_pos: pos |= {m.id for m in msgs if any(_meta_fns[k](m) for k in md_pos)}
    if pat_pos and not pat_neg: pos |= {m.id for m in msgs if _content_match(m, pat_pos, use_case, use_regex)}
    neg = set()
    if mt_neg: neg |= {m.id for m in msgs if m.msg_type in mt_neg}
    if md_neg: neg |= {m.id for m in msgs if any(_meta_fns[k](m) for k in md_neg)}
    if pat_neg: neg |= {m.id for m in msgs if _content_match(m, pat_pos, use_case, use_regex)}
    base = pos if has_pos else {m.id for m in msgs}
    return [m for m in msgs if m.id in base - neg]

# %% ../nbs/01_dialog.ipynb #ad25c0ee
async def filter_msgs_v2(
    msgs:list[Msg]=None, # List of messages to filter or None to use all messages.
    ids:str|list=None, # Message ids to include (union with section).
    section:str|list=None, # Section patterns to include (union with ids).
    msg_type:str|list=None, # Message types to include.
    metadata:str|list=None, # Metadata keys to to filter on ('exported', 'echo', 'header', 'hidden').
    re_pattern:str='', # Optional regex to search for (re.DOTALL+re.MULTILINE is used).
    use_case:bool=False, # Use case-sensitive matching?
    use_regex:bool=True, # Use regex matching?
    dname:str='', # Dialog to get messages for; defaults to current dialog.
) -> list[MsgX]:
    "Two-phase filter: scope by ids/section, then OR-filter by type/metadata/pattern with ! negation."
    if not any([ids is not None, section, msg_type, metadata, re_pattern]): return []
    msgs = msgs or await find_msgs_x(include_skipped=True, dname=dname)
    return _filter_pos_neg(_scope_msgs(msgs, ids, section), msg_type, metadata, re_pattern, use_case, use_regex)

# %% ../nbs/01_dialog.ipynb #c15da14e
def _r(m:dict, **kwargs):
    "Add kwargs to m and filter out key/value not compatible with add_msg or update_msg"
    if kwargs: m.update(kwargs)
    if m.msg_type == 'code': m.output = ''
    return dict(content=m.content, msg_type=m.msg_type, output=m.output, is_exported=m.is_exported, skipped=m.skipped, pinned=m.pinned, i_collapsed=m.i_collapsed, o_collapsed=m.o_collapsed, heading_collapsed=m.heading_collapsed)

# %% ../nbs/01_dialog.ipynb #45e21daf
def find_symbol_msg(msgs, sym:str) -> dict|None:
    "Find last message in msgs list containing symbol definition (module level)"
    for m in reversed(msgs):
        if m.msg_type != 'code': continue
        root = ast_py(m.content)
        for node in root.find_all(pattern='def $FUNC($$$)'):
            if node.field('name').text() == sym: return m
        for node in root.find_all(pattern='class $CLASS'):
            if node.field('name').text() == sym: return m
        for node in root.find_all(pattern='$VAR = $$$'):
            if node.field('left').text() == sym: return m
    return None

# %% ../nbs/01_dialog.ipynb #10fdfa3c
async def importdlg(
    dname:str='',  # dialog to import from; relative to solveit root (if starts with /) or current dialog; empty string for current dialog
    syms:list[str]=None,  # symbol names to import (finds last def/class/assignment); if provided, regex is ignored
    ids:list[str]=None,  # message ids to import; can combine with syms; if syms or ids provided, regex is ignored
    re_include:str=None,  # regex to filter messages (content+output); only used if no syms/ids; uses re.MULTILINE|re.DOTALL
    re_exclude:str=None,  # regex to exclude from re_include results; only used if no syms/ids
    run:bool=False,  # run imported messages after insertion
    header:bool=False,  # wrap imports in collapsed header with dialog name
    heading_collapsed:bool=False  # collapse the header after creation
):
    "Import messages from dname by symbols, ids, regex filter, or all messages; inserts below current message in original order"
    msgs, to_import = await find_msgs(dname=dname, include_meta=True, include_output=True), []
    if not dname: msgs = msgs[:await msg_idx()]
    if syms or ids:
        id2idx, seen = {m.id:i for i,m in enumerate(msgs)}, set()
        if syms:
            for sym in syms:
                if (m := find_symbol_msg(msgs, sym)) and m.id not in seen: to_import.append(m); seen.add(m.id)
        if ids:
            for m in msgs:
                if m.id in ids and m.id not in seen: to_import.append(m); seen.add(m.id)
        to_import.sort(key=lambda m: id2idx[m.id])
    else:
        to_import = msgs
        if re_include: to_import = [m for m in to_import if re.search(re_include, m.content + m.output, re.MULTILINE | re.DOTALL)]
        if re_exclude: to_import = [m for m in to_import if not re.search(re_exclude, m.content + m.output, re.MULTILINE | re.DOTALL)]
    new_ids = [await add_msg(**_r(m)) for m in to_import]
    if header and new_ids: 
        hdrid = await add_msg(f"## Imported from {dname}", placement='add_before', id=new_ids[0])
        new_ids.insert(0, hdrid)
        new_ids.append(await add_msg("## ----", id=new_ids[-1]))
    # time.sleep(0.5)
    if run and new_ids: await run_msg(','.join(new_ids))
    # time.sleep(0.1)
    if heading_collapsed and header: await toggle_header(hdrid)
    return new_ids

# %% ../nbs/01_dialog.ipynb #fa95098d
def nb_path(dname:str=''): return (Path.home()/(dname or find_dname()).removeprefix('/')).with_suffix('.ipynb')

# %% ../nbs/01_dialog.ipynb #ea22a822
_exp_pat =r'^\s*#\s*\|\s*default_exp\s+(\w+)'
async def dlg_module(dname:str=''):
    msgs = await find_msgs(_exp_pat, dname=(dname or find_dname()), limit=1, include_output=False, include_meta=False)
    if msgs: return msgs[0].content.strip().split()[-1]

# %% ../nbs/01_dialog.ipynb #08c30808
def dlg_export(dname:str=''):
    "Export dialog `dname` to Python module"
    dlg_path = (Path.home()/(find_dname().removeprefix('/'))).with_suffix(".ipynb")
    from nbdev.export import nb_export
    nb_export(dlg_path)
    return dlg_path.exists()

# %% ../nbs/01_dialog.ipynb #307fd9c6
def get_dialog_link(
    path:str # Path to dialog (e.g. '/aai-ws/dialoghelper/nbs/00_core')
) -> str:
    "Return an HTML link to open a dialog in Solveit."
    from dialoghelper.core import dialog_link
    return dialog_link(path).data

# %% ../nbs/01_dialog.ipynb #40bdbb0e
def empty_dialog_nb() -> str:
    "Return a minimal dialog notebook json"
    return '''
{
"cells": [],
"metadata": {
"solveit_dialog_mode": "learning",
"solveit_ver": 2
},
"nbformat": 4,
"nbformat_minor": 5
}
'''

# %% ../nbs/01_dialog.ipynb #f9e951f2
async def get_msg_id():
    "Get current message id."
    return (await read_msg(0)).id

# %% ../nbs/01_dialog.ipynb #480c7b40
@delegates(read_msg)
async def get_output(id:str=None, **kwargs) -> list[str]:
    msg = await read_msg(0, id=id, **kwargs)
    return msg.output

# %% ../nbs/01_dialog.ipynb #e81a8806
_format = get_ipython().display_formatter.format if in_dialog() else None

# %% ../nbs/01_dialog.ipynb #35c391be
delegates(_format)
def format_output(o, **kwargs):
  d, md = _format(o, **kwargs) if _format else ('', {})
  return json.dumps([{"data": d, "metadata": md, "output_type": "display_data"}])

# %% ../nbs/01_dialog.ipynb #c6cb05f6
def split_md_blocks(md):
    "Split markdown into fenced/non-fenced blocks via mistletoe AST"
    with MarkdownRenderer() as renderer:
        doc = Document(md)
        blocks,buf = [],[]
        for c in doc.children:
            if isinstance(c, CodeFence):
                if buf: blocks.append(''.join(buf)); buf = []
                blocks.append(renderer.render(c))
            else: buf.append(renderer.render(c))
        if buf: blocks.append(''.join(buf))
        return blocks
