"""display helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_display.ipynb.

# %% auto #0
__all__ = ['ESC', 'sgr', 'color_table', 'color_codes', 'add_style', 'list2lis', 'dict2uls', 'dict2dtls', 'DetailsColl',
           'DetailsJSON', 'DfTable']

# %% ../nbs/02_display.ipynb #5c7f7c5b
from typing import Mapping, Sequence
import pandas as pd
from fastcore.xml import FT
from fasthtml.common import camel2words, snake2camel
from fasthtml.components import Div, Details, Summary, Ul, Li, Span, show, Td, Th, Table, Thead, Tr, Tbody
from fasthtml.xtend import Style
from dialoghelper.core import add_html
from .common import is_listy, flatten, shorten

# %% ../nbs/02_display.ipynb #0fac6dfb
_n = '\n'

# %% ../nbs/02_display.ipynb #1c1435f2
ESC = '\033['
def sgr(*c): return f"{ESC}{';'.join(map(str,c))}m"

def color_table():
    fgs   = [30,31,32,33,34,35,36,37]
    fgs_i = [90,91,92,93,94,95,96,97]
    bgs = [('(none)',49),('bg-black',40),('+ intense',100),('bg-red',41),('+ intense',101),
           ('bg-green',42),('+ intense',102),('bg-yellow',43),('+ intense',103),
           ('bg-blue',44),('+ intense',104),('bg-magenta',45),('+ intense',105),
           ('bg-cyan',46),('+ intense',106),('bg-white',47),('+ intense',107)]
    def cell(fg, fg_i, bg):
        return (sgr(bg,fg)+sgr(2)+'f'+sgr(22)+'n'+sgr(1)+'b'+sgr(22) +
                sgr(fg_i)+sgr(2)+'F'+sgr(22)+'N'+sgr(1)+'B'+sgr(22)+sgr(0))
    print(f"{'':12} black   red  green  yellow  blue  magenta cyan   white")
    for lbl, bg in bgs:
        print(f'{lbl:<12}' + ' '.join(cell(fg, fg_i, bg) for fg,fg_i in zip(fgs,fgs_i)))

# %% ../nbs/02_display.ipynb #6c989119
def color_codes():
    def patch(code): return f"{sgr(48,5,code)} {code:3} {sgr(49)}"
    
    print('Standard: ' + sgr(1) + sgr(37) + ''.join(patch(c) + (sgr(30) if c==6 else '') for c in range(8)) + sgr(0))
    print('Intense:  ' + sgr(37) + ''.join(patch(c) + (sgr(30) if c==8 else '') for c in range(8,16)) + sgr(0))
    print()
    for i in [16, 22, 28]:
        for j in [i, i+36, i+72, i+108, i+144, i+180]:
            print(sgr(1,37) + ''.join(patch(c) for c in range(j,j+6)) + sgr(0) + '    ' +
                  sgr(30) + ''.join(patch(c) for c in range(j+18,j+24)) + sgr(0))
        print()
    print('Grays:    ' + sgr(1,37) + ''.join(patch(c) for c in range(232,244)) + sgr(0))
    print('          ' + sgr(30)   + ''.join(patch(c) for c in range(244,256)) + sgr(0))

# %% ../nbs/02_display.ipynb #4ac7544e
def add_style(css:str):
    _stl = Div(Style(css), hx_swap_oob='beforeend:#dialog-container')
    add_html(_stl)

# %% ../nbs/02_display.ipynb #82de485a
def it2lbl(it, nm=''):
    # return ((nm, it) if nm else (it,)) if isinstance(it, FT) else (str(it),)
    it = it if isinstance(it, FT) else str(it)
    return (nm, it) if nm else (it,)

# %% ../nbs/02_display.ipynb #064d0905
def list2lis(its:list, dproc, eproc=it2lbl) -> list[Li]:
    return flatten([
        [Li(data_it=True)(*eproc(ul,k)) for k,ul in dproc(it).items()] if isinstance(it, dict) else
        Li(data_it=True)(*eproc(it))
        for it in its], (FT,))

def dict2uls(d:dict, eproc=it2lbl) -> dict[Ul]:
    return {
        k:Ul(data_coll_name=k)(*list2lis(v if is_listy(v) else [v], dict2uls, eproc)) 
        for k,v in d.items()
    }

# %% ../nbs/02_display.ipynb #e079b695
def it2lbl2(it, nm=''):
    return (it,) if isinstance(it, FT) else (str(it),)

# %% ../nbs/02_display.ipynb #3f3b7bf2
def dict2dtls(d:dict, eproc=it2lbl2) -> dict[Details]:
    return {
        k:Details(open=True, data_coll_name=k)(
            Summary(k),
            Ul()(*list2lis(v if is_listy(v) else [v], dict2dtls, eproc))
        )
        for k,v in d.items()
    }

# %% ../nbs/02_display.ipynb #5d23c6de
_css_coll = '''
.coll ul { list-style-type:none; list-style-position: outside; padding-inline-start: 22px; margin: 0px; }
.coll .None { color: gray; }
'''
#| linkedto: _f292d92c

# %% ../nbs/02_display.ipynb #14b6bcb0
class DetailsColl(dict):
    "Interactive collapsible collection viewer with HTML details/summary structure"
    def __init__(self, d, summary:str='', open:bool=True, openall:bool=False):
        super().__init__(d or {})
        self.summary, self.open, self.openall = str(summary), open, openall
    def show(self): show(self)
    def __ft__(self, its=None, summary:str|None=None, lvl:int=0, open:bool=False):
        return Div(*dict2dtls(self).values(), cls='coll')
    _css_ = _css_coll
    @classmethod
    def setup_style(cls): add_style(cls._css_)

# %% ../nbs/02_display.ipynb #37179556
def Val(v): 
    "Render value with appropriate CSS class based on type"
    c = (
        'null' if v is None else 
        'true' if v is True else 
        'false' if v is False else 
        'string' if isinstance(v, str) else 
        'number' if isinstance(v, (int, float)) else 
        '')
    return Span(shorten(v, 'r', 140) if v is not None else 'None', cls=f"v {c}")

# %% ../nbs/02_display.ipynb #cf238895
def NameVal(k, v):
    "Render key-value pair with name and value styling"
    return Span(Span(k, cls='n'), ': ', Val(v))

# %% ../nbs/02_display.ipynb #436822e5
_css_json = (
    'details.json ul { list-style-type:none; list-style-position: outside; padding-inline-start: 22px; margin: 0; } '
    '''details.json .string { color: #24837b; } details.json .string::before { content: "'"; } details.json .string::after { content: "'"; } '''
    'details.json .number { color: #ad8301; } '
    'details.json .true { color: blue; } '
    'details.json .false { color: red; } '
    'details.json .null { color: gray; } '
    'details.json span.n { color: darkgrey; } '
)


# %% ../nbs/02_display.ipynb #98ae5311
class DetailsJSON(dict):
    "Interactive collapsible JSON viewer with HTML details/summary structure"
    def __init__(self, *args, summary:str='', open:bool=True, openall:bool=False, skip:Sequence[str]=(), **kwargs):
        super().__init__(*args, **kwargs)
        self.summary, self.open, self.openall, self.skip = str(summary), open, openall, skip
    def show(self): show(self)
    def __ft__(self, d:Mapping|None=None, summary:str|None=None, lvl:int=0, open:bool=False):
        if d is None: d = self; summary = self.summary or 'summary'; open=self.open
        open = self.openall or open
        return (
            Details(open=open, cls="json")(
                Summary(summary, _n),
                Ul()(*(
                    Li(NameVal(k, v)) if k in self.skip else
                    self.__ft__(v, k, lvl+1) if isinstance(v, Mapping) else
                    self.__ft__(dict(list(zip(range(len(v)), v))), k, lvl+1) if is_listy(v) else
                    Li(NameVal(k, v)) 
                    for k,v in d.items()))))
    _css_ = _css_json
    @classmethod
    def setup_style(cls): add_style(cls._css_)

# %% ../nbs/02_display.ipynb #1203f111
DetailsJSON.setup_style()

# %% ../nbs/02_display.ipynb #91e320ce
def DfTable(df=None, fmt_fns=(), col_cls=(), sz="xs", cls="", **kw):
    fmt_fns = dict(fmt_fns)
    col_cls = dict(col_cls)

    def render(df):
        def snake2words(o): return camel2words(snake2camel(o))    
        def to_cls(n): return "tabular-nums text-right" if pd.api.types.is_any_real_numeric_dtype(df[n].dtype) else "text-left"

        def fmt_fn(n):
            t = df[n].dtype
            def blank_na(f): return lambda x: "" if pd.isna(x) else f(x)
            if pd.api.types.is_integer_dtype(t): return blank_na(lambda x:f"{x:,.0f}")
            if pd.api.types.is_any_real_numeric_dtype(t): return blank_na(lambda x:f"{x:,.2f}")
            if pd.api.types.is_datetime64_any_dtype(t): return blank_na(lambda x:pd.Timestamp(x).strftime("%b %d, %Y"))
            if pd.api.types.is_bool_dtype(t): return blank_na(lambda x: "Yes" if x else "No")
            return blank_na(lambda x: str(x).strip())

        def mk_td(name, val):
            return Td(cls=f"{to_cls(name)} {col_cls.get(name, '')}".strip())(fmt_fns.get(name, fmt_fn(name))(val))

        def mk_th(o): return Th(cls=f"{to_cls(o)} whitespace-nowrap")(snake2words(o).title())

        tbl_cls = f"{cls} table table-{sz} table-zebra table-pin-cols table-pin-rows"

        return Table(cls=tbl_cls, **kw)(
            Thead(Tr(*map(mk_th, df.dtypes.to_dict()))),
            Tbody(*df.apply(lambda o:Tr(*[mk_td(n,v) for n,v in zip(o.index, o)]), axis=1).to_list()),
        )
        

    return render if df is None else render(df)
