"""display helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_display.ipynb.

# %% auto #0
__all__ = ['Val', 'NameVal', 'DetailsJSON']

# %% ../nbs/01_display.ipynb #5c7f7c5b
from typing import Mapping, Sequence
from fasthtml.common import show
from fasthtml.components import Div, Details, Summary, Ul, Li, Span
from fasthtml.xtend import Style
from dialoghelper.core import add_html
from .common import is_listy, shorten

# %% ../nbs/01_display.ipynb #0fac6dfb
_n = '\n'

# %% ../nbs/01_display.ipynb #86c34902
def Val(v): 
    "Render value with appropriate CSS class based on type"
    c = (
        'null' if v is None else 
        'true' if v is True else 
        'false' if v is False else 
        'string' if isinstance(v, str) else 
        'number' if isinstance(v, (int, float)) else 
        '')
    return Span(shorten(v, 'r', 140) if v is not None else 'None', cls=f"v {c}")

# %% ../nbs/01_display.ipynb #5c0c331f
def NameVal(k, v):
    "Render key-value pair with name and value styling"
    return Span(Span(k, cls='n'), ': ', Val(v))

# %% ../nbs/01_display.ipynb #5a1f6f13
class DetailsJSON(dict):
    "Interactive collapsible JSON viewer with HTML details/summary structure"
    def __init__(self, *args, summary:str='', open:bool=True, openall:bool=False, skip:Sequence[str]=(), **kwargs):
        super().__init__(*args, **kwargs)
        self.summary, self.open, self.openall, self.skip = str(summary), open, openall, skip
    def show(self): show(self)
    def __ft__(self, d:Mapping|None=None, summary:str|None=None, lvl:int=0, open:bool=False):
        if d is None: d = self; summary = self.summary or 'summary'; open=self.open
        open = self.openall or open
        return (
            # Style(self._css_) if lvl == 0 else (), 
            Details(open=open, cls="json")(
                Summary(summary, _n),
                Ul()(*(
                    Li(NameVal(k, v)) if k in self.skip else
                    self.__ft__(v, k, lvl+1) if isinstance(v, Mapping) else
                    self.__ft__(dict(list(zip(range(len(v)), v))), k, lvl+1) if is_listy(v) else
                    Li(NameVal(k, v)) 
                    for k,v in d.items()))))
    # _css_ = 'details ul { list-style-type:none; list-style-position: outside; padding-inline-start: 22px; margin: 0; } '
    _css_ = (
        'details.json ul { list-style-type:none; list-style-position: outside; padding-inline-start: 22px; margin: 0; } '
        '''details.json .string { color: #24837b; } details.json .string::before { content: "'"; } details.json .string::after { content: "'"; } '''
        'details.json .number { color: #ad8301; } '
        'details.json .true { color: blue; } '
        'details.json .false { color: red; } '
        'details.json .null { color: gray; } '
        'details.json span.n { color: darkgrey; } '
    )
    @classmethod
    def setup_style(cls):
        _stl = Div(Style(cls._css_), hx_swap_oob='beforeend:#dialog-container')
        add_html(_stl)

# %% ../nbs/01_display.ipynb #4de3c818
DetailsJSON.setup_style()
