"""Solveit basic helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_dutil.ipynb.

# %% auto #0
__all__ = ['setup_dialog', 'solveit_version', 'in_dialog', 'get_caller_globals', 'get_msg_id', 'get_output', 'format_output',
           'set_var', 'find_var', 'get_tag', 'has_tag', 'find_tag', 'get_linked', 'link_msg', 'hydrate', 'waitpred',
           'waitpreda', 'next_dup', 'next_filename', 'gen_id', 'at_', 'setup_ns', 'info', 'add_info', 'summarize',
           'get_tool_names', 'show_tool_names', 'mk_ns_toollist', 'add_tools_card', 'is_exported', 'nb_path',
           'dlg_module', 'dlg_export', 'get_dialog_link', 'ctxusage', 'empty_dialog_nb', 'find_symbol_msg', 'importdlg']

# %% ../nbs/00_dutil.ipynb #e72f67fd
import os, re, sys, inspect, uuid, json, time
from collections import defaultdict
from inspect import Parameter, currentframe
from pathlib import Path
from typing import Any, Mapping
from IPython import get_ipython
from anyio import sleep
from anyio.from_thread import start_blocking_portal
from nbdev.process import extract_directives
from fastcore.imports import in_ipython
from fastcore.foundation import AttrDict
from fastcore.meta import delegates
from fastcore.xtras import is_listy
import dialoghelper
from dialoghelper.core import add_msg, is_usable_tool, read_msg, update_msg, find_msgs, msg_idx, run_msg, toggle_header, ast_py, find_dname
from toolslm.funccall import get_schema, resolve_nm
from fastgit import Git

# %% ../nbs/00_dutil.ipynb #6389d58d
def solveit_version():
    "Return the version of solveit if it is found"
    s = ' '.join(_.__module__ for _ in sys.meta_path)
    mtch = re.match(r'.*__editable___solveit_(\d+)_(\d+)_(\d+)_finder', s)
    return f"{mtch[1]}.{mtch[2]}.{mtch[3]}" if mtch else ''

# %% ../nbs/00_dutil.ipynb #85a58913
def in_dialog():
    "Check if the code is running in a solveit dialog"
    if not (os.environ.get('IN_SOLVEIT') and in_ipython() and bool(solveit_version())): return False
    try:
        if find_dname(): return True
    except: pass
    return False

# %% ../nbs/00_dutil.ipynb #a0c6cf33
def get_caller_globals(): 
    "Return the globals of the caller"
    return inspect.currentframe().f_back.f_globals

# %% ../nbs/00_dutil.ipynb #f9e951f2
async def get_msg_id():
    "Get current message id."
    return (await read_msg(0)).id

# %% ../nbs/00_dutil.ipynb #480c7b40
@delegates(read_msg)
async def get_output(id:str=None, **kwargs) -> list[str]:
    msg = await read_msg(0, id=id, **kwargs)
    return msg.output

# %% ../nbs/00_dutil.ipynb #e81a8806
_format = get_ipython().display_formatter.format if in_dialog() else None

# %% ../nbs/00_dutil.ipynb #35c391be
delegates(_format)
def format_output(o, **kwargs):
  d, md = _format(o, **kwargs) if _format else ('', {})
  return json.dumps([{"data": d, "metadata": md, "output_type": "display_data"}])

# %% ../nbs/00_dutil.ipynb #e45e9175
# old version from `dialoghelper`, not thread safe
def _find_frame_dict(sentinel:str):
    "Find the globals dict containing sentinel, or calling frame's globals if no sentinel"
    frame = currentframe().f_back.f_back
    if not sentinel: return frame.f_globals
    while frame:
        if sentinel in frame.f_globals: return frame.f_globals
        frame = frame.f_back
    return globals()

def set_var(var:str, val, force:bool=False):
    "Set var to val after finding it in all frames of the call stack"
    frame = _find_frame_dict(var)
    if var not in frame and not force: raise ValueError(f"Could not find {var} in any scope")
    frame[var] = val

def find_var(var:str, default:Any=Parameter.empty):
    "Search for var in all frames of the call stack"
    if var in (frame := _find_frame_dict(var)): return frame[var]
    return default
find_var.notfound = Parameter.empty

# %% ../nbs/00_dutil.ipynb #3a1d4063
_ts, _te = ('<!-- ', '#| '), (' -->', '')
async def get_tag(name:str, val:str='', msg_type:str='note'):
    return f"{_ts[msg_type=='code']}{name}: {val or await get_msg_id()}{_te[msg_type=='code']}"

# %% ../nbs/00_dutil.ipynb #bd2da5c6
_tagpats = {
    'code': (re.compile(r'\A#\|\W*(\w+): ([_a-f0-9]{9})\W*$', re.MULTILINE),
             re.compile(r'^#\|\W*(\w+): ([_a-f0-9]{9})\W*\Z', re.MULTILINE)),
    'note': (re.compile(r'\A<!-- (\w+): ([_a-f0-9]{9}) -->\W*$', re.MULTILINE),
             re.compile(r'^<!-- (\w+): ([_a-f0-9]{9}) -->\s*\Z', re.MULTILINE))
}
_tagpats['raw'] = _tagpats['prompt'] = _tagpats['note']
_tagpats[None] = _tagpats['note'] + _tagpats['code']

def has_tag(s:str, msg_type:str=None) -> bool:
    "Check if string contains tags created by get_tag at the start or end of the string"
    if msg_type == 'code' and not (s.startswith('#|') or '\n#|' in s): return False
    if msg_type == 'note' and not (s.startswith('<!--') or '\n<!--' in s): return False
    return any(re.search(pat, s) for pat in _tagpats[msg_type])

# %% ../nbs/00_dutil.ipynb #070879cc
def find_tag(s: str, msg_type: str = None) -> str:
    "Find tag in a string and return their details"
    for pat in _tagpats[msg_type]:
        if match := re.search(pat, s): return f"{match.group(1)}: {match.group(2)}"
    return ''

# %% ../nbs/00_dutil.ipynb #c8a25aeb
async def get_linked(id:str) -> str:
    if (msg := (await read_msg(0, id=id))).get('id','') == id:
        if tag := find_tag(msg.content, msg.msg_type):
            k,v = tag.split(': ')
            if k == 'linkedto': return v
    return ''

# %% ../nbs/00_dutil.ipynb #6b6c1b31
if in_dialog() and __name__ != '__main__': get_ipython().xpush(__linked_msgs={})

# %% ../nbs/00_dutil.ipynb #69fd0e09
delegates(add_msg)
async def link_msg(
    content:str=None,  # Content of the linked message
    id:str=None,  # ID of the message to link to, or current message if not provided
    pos:str='end',  # Position of the tag in the message
    **kwargs  # Additional keyword arguments for `add_msg` or `update_msg`
) -> str:  # id of linked message
    "Add or update a message linked to `anchor` message. Note only one linked msg per anchor."
    anchor_id, linked = id or await get_msg_id(), find_var('__linked_msgs')
    def _with_tag(tag, c): return f"{tag}\n{c}" if pos=='start' else f"{c}\n{tag}"
    if linked_id := linked.get(anchor_id):
        if (msg := await read_msg(0, id=linked_id)).get('id','') == linked_id:
            tag = await get_tag('linkedto', anchor_id, kwargs.get('msg_type', msg.msg_type))
            if content: kwargs['content'] = _with_tag(tag, content)
            linked[anchor_id] = await update_msg(linked_id, **kwargs)
            return linked[anchor_id]
    tag = await get_tag('linkedto', anchor_id, kwargs.get('msg_type', 'note'))
    linked[anchor_id] = await add_msg(_with_tag(tag, content or '.'), id=anchor_id, **kwargs)  # NOTE: bug note message w/ only comment
    return linked[anchor_id]

# %% ../nbs/00_dutil.ipynb #dab704aa
async def hydrate():
    "Traverse dialog looking for linked messages to update `__linked_msgs`"
    linked = find_var('__linked_msgs')
    linked.clear()
    msgs = await find_msgs(include_meta=True, include_output=False, include_skipped=True)
    ids = {_.id for _ in msgs}
    for msg in msgs:
        if tag := find_tag(msg.get('content', ''), msg.get('msg_type')):
            k, v = tag.split(': ')
            if k == 'linkedto' and v in ids: linked[v] = msg['id']
    return linked

# %% ../nbs/00_dutil.ipynb #b9ae31c1
def waitpred(pred, timeout=0.5, interval=0.05):
    "Wait until `pred` is True or `timeout` is reached without blocking the kernel"
    async def _wait():
        start = time.time()
        while time.time()-start < timeout and not pred(): await sleep(interval)
        return pred()
    with start_blocking_portal() as portal: return portal.call(_wait)

# %% ../nbs/00_dutil.ipynb #c334d7b2
async def waitpreda(pred, timeout=0.5, interval=0.05):
    "Async wait until `pred` is True or `timeout` is reached without blocking the kernel"
    t0 = time.time()
    while not await pred():
        if time.time() - t0 > timeout: return False
        await sleep(0.1)
    return True

# %% ../nbs/00_dutil.ipynb #cc011438
def next_dup(fp, marker='_dup'):
    "Get next available duplicate number in fp parent directory"
    fp = Path(fp)
    p, nm, suff = fp.parent, fp.stem.split('.')[0], ''.join(fp.suffixes)
    nm = m[1] if (m := re.match(r'^(.+)'+re.escape(marker)+r'\d+$', nm)) else nm
    # if not p.exists(): i, p/f"{nm}{marker}{i}{suff}"
    dupr = re.compile(r'^'+re.escape(nm+marker)+r'(\d+)$')
    nums = sorted({int(m[1]) for f in p.iterdir() if (m := re.match(dupr, f.stem.split('.')[0]))})
    # if not nums: return 0, p/f"{nm}{suff}"
    for i,n in enumerate(nums, 1):
        if i != n: return i, p/f"{nm}{marker}{i}{suff}"
    return len(nums)+1, p/f"{nm}{marker}{len(nums)+1}{suff}"



# %% ../nbs/00_dutil.ipynb #9ec1c746
def next_filename(path:str):
    "Get next available duplicate filename for path, e.g., 'img.jpg' -> 'img_dup1.jpg'"
    _,fp = next_dup(Path(path))
    return str(fp)

# %% ../nbs/00_dutil.ipynb #a537ff31
def gen_id(): return f"_{uuid.uuid4().hex[:8]}"

# %% ../nbs/00_dutil.ipynb #5a3f523f
_empty = inspect.Parameter.empty

# %% ../nbs/00_dutil.ipynb #f300a22f
def at_(
    o, # Object to traverse (dict, list, object, or nested combination)
    sym: str, # Path using dots and/or brackets (e.g., 'a.b[0].c' or 'a[b][c]')",
    default: Any=_empty, # Value to return if path not found (raises exception if not provided)
    sep='.' # Separator for path segments
) -> Any: # Value at the specified path
    "Traverse nested `o` using path `sym` with dot notation and/or bracket indexing"
    sym = re.sub(r'\[([^\]]+)\]', r'.\1', sym)
    try:
        for a in filter(None, sym.split(sep)):
            if a.lstrip('-').isdigit(): a = int(a)
            try: o = o[a]
            except Exception:
                if isinstance(a, int):
                    try: o = o[str(a)]; continue
                    except Exception: pass
                o = getattr(o, a)
    except Exception:
        if default is not _empty: return default
        raise
    return o

# %% ../nbs/00_dutil.ipynb #60e5b6e0
async def setup_ns(ns=None, **kwargs):
    "Add `kwargs` to the namespace `ns` or current dialog"
    ns = ns or _find_frame_dict('__dialog_name')
    # lc = list(locals().items())[1:]
    thisid = await get_msg_id()
    for k,v in kwargs.items(): ns[k] = v
    msgid = await link_msg('\n\n'.join(f"{k} = {v}" for k,v in kwargs.items()))
    print(thisid, msgid)

setup_dialog = setup_ns

# %% ../nbs/00_dutil.ipynb #64bf2039
def info():
    "Returns information about the dialog"
    ver = f"Solveit version: **{solveit_version()}**  \ndialoghelper version: **{dialoghelper.__version__}**  "
    gs = ''
    g = Git('.')
    if g.exists:
        br, *chngs = g('status', '-bs')
        gs = f"\ngit branch: **{br.split()[-1]}**  \ngit changes: {chngs}"
    return ver + gs

# %% ../nbs/00_dutil.ipynb #e2bc850b
async def add_info(msgid:str=''):
    "Add a message with information about the dialog"
    return await link_msg(info(), id=msgid)

# %% ../nbs/00_dutil.ipynb #8e88bb43
def summarize(target, context): pass

# %% ../nbs/00_dutil.ipynb #2f133f3b
def _get_ns(ns):
    if inspect.ismodule(ns): ns = vars(ns)
    elif isinstance(ns, str): ns = {k: get_ipython().user_ns[k] for _ in re.split(r'\s*,\s*', ns) if (k := _.strip())}
    return ns or get_ipython().user_ns

def get_tool_names(
    ns:Mapping|str=None,  # module,mapping,comma-separated str; None uses IPython user namespace
    exclude:Mapping|list[str]=None,  # module/mapping (recursively scanned) or list of symbol names to exclude
    only_exported:bool=False,  # if ns is a module, only include symbols in __all__
    exclude_private:bool=True  # exclude symbols starting with '_'
) -> dict[str,list[str]]:  # module name -> list of tool names
    "Return dict mapping module names to lists of usable tool names from namespace ns (or IPython user namespace if None)."
    ns = _get_ns(ns)
    if exclude: exclude = set(sum(get_tool_names(exclude).values(), []) if not is_listy(exclude) else exclude)
    res, vis, exports = defaultdict(list), defaultdict(set), set(ns.get('__all__', []))
    for k,v in ns.items():
        if exclude_private and k[0] == '_': continue
        if only_exported and k not in exports: continue
        if exclude and k in exclude: continue
        if not hasattr(__builtins__, k) and callable(v):
            try:
                if is_usable_tool(v): 
                    if inspect.isclass(v) and '__call__' not in v.__dict__: continue
                    if get_schema(v): 
                        mod = getattr(v, '__module__', 'unknown')
                        if v not in vis[mod]: res[mod].append(k); vis[mod].add(v)
            except Exception: pass
    return dict(res)

# %% ../nbs/00_dutil.ipynb #c7389abd
delegates(get_tool_names)
def show_tool_names(*args, **kwargs):
    for mn,syms in get_tool_names(*args, **kwargs).items():
        print(mn)
        print('  ', ', '.join(syms))

# %% ../nbs/00_dutil.ipynb #7fca2fc7
def mk_ns_toollist(ns, nms):
    ns = _get_ns(ns)
    return "\n".join(f"- &`{nm}`: {resolve_nm(nm, ns).__doc__}" for nm in nms)

# %% ../nbs/00_dutil.ipynb #e19bcfdf
delegates(get_tool_names)
async def add_tools_card(ns:Mapping|str=None, **kwargs):
    "Add a message with all tools in namespace `ns` or caller globals"
    ns = _get_ns(ns)
    mod2tool = get_tool_names(ns, **kwargs)
    content = '\n\n'.join(f"## {mod}\n\n{mk_ns_toollist(ns, tools)}" for mod,tools in mod2tool.items())
    await link_msg(content)

# %% ../nbs/00_dutil.ipynb #9b570c54
_exports = {'exporti', 'exports', 'export'}

# %% ../nbs/00_dutil.ipynb #adad19c4
def is_exported(msg):
    return msg.is_exported or bool(
        extract_directives(AttrDict(source=msg.content), remove=False).keys() & _exports)

# %% ../nbs/00_dutil.ipynb #5a13b503
def nb_path(dname:str=''): return (Path.home()/(dname or find_dname()).removeprefix('/')).with_suffix('.ipynb')

# %% ../nbs/00_dutil.ipynb #801eec3c
_exp_pat =r'^\s*#\s*\|\s*default_exp\s+(\w+)'
async def dlg_module(dname:str=''):
    msgs = await find_msgs(_exp_pat, dname=(dname or find_dname()), limit=1, include_output=False, include_meta=False)
    if msgs: return msgs[0].content.strip().split()[-1]

# %% ../nbs/00_dutil.ipynb #85debf85
def dlg_export(dname:str=''):
    "Export dialog `dname` to Python module"
    dlg_path = (Path.home()/(find_dname().removeprefix('/'))).with_suffix(".ipynb")
    from nbdev.export import nb_export
    nb_export(dlg_path)
    return dlg_path.exists()

# %% ../nbs/00_dutil.ipynb #f6dfc50c
def get_dialog_link(
    path:str # Path to dialog (e.g. '/aai-ws/dialoghelper/nbs/00_core')
) -> str:
    "Return an HTML link to open a dialog in Solveit."
    from dialoghelper.core import dialog_link
    return dialog_link(path).data

# %% ../nbs/00_dutil.ipynb #2b349e8c
async def ctxusage(id:str='', dname:str=''):
    msgs = await find_msgs(include_output=False, dname=dname)
    id = id or await get_msg_id()
    pos = await msg_idx(id)
    return sum(m.input_tokens + (m.output_tokens or 0) for m in msgs[:pos] if not m.skipped)

# %% ../nbs/00_dutil.ipynb #0f89451e
def empty_dialog_nb() -> str:
    "Return a minimal dialog notebook json"
    return '''
{
"cells": [],
"metadata": {
"solveit_dialog_mode": "learning",
"solveit_ver": 2
},
"nbformat": 4,
"nbformat_minor": 5
}
'''

# %% ../nbs/00_dutil.ipynb #a96b3c40
def _r(m:dict, **kwargs):
    "Add kwargs to m and filter out key/value not compatible with add_msg or update_msg"
    if kwargs: m.update(kwargs)
    if m.msg_type == 'code': m.output = ''
    return dict(content=m.content, msg_type=m.msg_type, output=m.output, is_exported=m.is_exported, skipped=m.skipped, pinned=m.pinned, i_collapsed=m.i_collapsed, o_collapsed=m.o_collapsed, heading_collapsed=m.heading_collapsed)

# %% ../nbs/00_dutil.ipynb #aea4f976
def find_symbol_msg(msgs, sym:str) -> dict|None:
    "Find last message in msgs list containing symbol definition (module level)"
    for m in reversed(msgs):
        if m.msg_type != 'code': continue
        root = ast_py(m.content)
        for node in root.find_all(pattern='def $FUNC($$$)'):
            if node.field('name').text() == sym: return m
        for node in root.find_all(pattern='class $CLASS'):
            if node.field('name').text() == sym: return m
        for node in root.find_all(pattern='$VAR = $$$'):
            if node.field('left').text() == sym: return m
    return None

# %% ../nbs/00_dutil.ipynb #6524b978
async def importdlg(
    dname:str='',  # dialog to import from; relative to solveit root (if starts with /) or current dialog; empty string for current dialog
    syms:list[str]=None,  # symbol names to import (finds last def/class/assignment); if provided, regex is ignored
    ids:list[str]=None,  # message ids to import; can combine with syms; if syms or ids provided, regex is ignored
    re_include:str=None,  # regex to filter messages (content+output); only used if no syms/ids; uses re.MULTILINE|re.DOTALL
    re_exclude:str=None,  # regex to exclude from re_include results; only used if no syms/ids
    run:bool=False,  # run imported messages after insertion
    header:bool=False,  # wrap imports in collapsed header with dialog name
    heading_collapsed:bool=False  # collapse the header after creation
):
    "Import messages from dname by symbols, ids, regex filter, or all messages; inserts below current message in original order"
    msgs, to_import = await find_msgs(dname=dname, include_meta=True, include_output=True), []
    if not dname: msgs = msgs[:await msg_idx()]
    if syms or ids:
        id2idx, seen = {m.id:i for i,m in enumerate(msgs)}, set()
        if syms:
            for sym in syms:
                if (m := find_symbol_msg(msgs, sym)) and m.id not in seen: to_import.append(m); seen.add(m.id)
        if ids:
            for m in msgs:
                if m.id in ids and m.id not in seen: to_import.append(m); seen.add(m.id)
        to_import.sort(key=lambda m: id2idx[m.id])
    else:
        to_import = msgs
        if re_include: to_import = [m for m in to_import if re.search(re_include, m.content + m.output, re.MULTILINE | re.DOTALL)]
        if re_exclude: to_import = [m for m in to_import if not re.search(re_exclude, m.content + m.output, re.MULTILINE | re.DOTALL)]
    new_ids = [await add_msg(**_r(m)) for m in to_import]
    if header and new_ids: 
        hdrid = await add_msg(f"## Imported from {dname}", placement='add_before', id=new_ids[0])
        new_ids.insert(0, hdrid)
        new_ids.append(await add_msg("## ----", id=new_ids[-1]))
    # time.sleep(0.5)
    if run and new_ids: await run_msg(','.join(new_ids))
    # time.sleep(0.1)
    if heading_collapsed and header: await toggle_header(hdrid)
    return new_ids
