"""core provides dialog introspection, message linking, tool discovery, and import/export utilities for solveit dialogs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_dutil.ipynb.

# %% auto #0
__all__ = ['setup_dialog', 'solveit_version', 'in_dialog', 'get_caller_globals', 'ctxusage', 'set_var', 'find_var', 'get_tag',
           'has_tag', 'find_tag', 'get_linked', 'link_msg', 'hydrate', 'waitpred', 'waitpreda', 'next_dup',
           'next_filename', 'gen_id', 'at_', 'setup_ns', 'info', 'add_info', 'summarize', 'get_tool_names',
           'show_tool_names', 'mk_ns_toollist', 'add_tools_card']

# %% ../nbs/00_dutil.ipynb #1e28a183
import os, re, sys, inspect, uuid, time
from collections import defaultdict
from inspect import Parameter, currentframe
from pathlib import Path
from typing import Any, Mapping
from IPython import get_ipython
from anyio import sleep
from anyio.from_thread import start_blocking_portal
from fastcore.imports import in_ipython
from fastcore.meta import delegates
from fastcore.xtras import is_listy
import dialoghelper
from dialoghelper.core import add_msg, is_usable_tool, msg_idx, read_msg, update_msg, find_msgs, find_dname
from toolslm.funccall import get_schema, resolve_nm
from fastgit import Git

# %% ../nbs/00_dutil.ipynb #6389d58d
def solveit_version():
    "Return the version of solveit if it is found"
    s = ' '.join(_.__module__ for _ in sys.meta_path)
    mtch = re.match(r'.*__editable___solveit_(\d+)_(\d+)_(\d+)_finder', s)
    return f"{mtch[1]}.{mtch[2]}.{mtch[3]}" if mtch else ''

# %% ../nbs/00_dutil.ipynb #85a58913
def in_dialog():
    "Check if the code is running in a solveit dialog"
    if not (os.environ.get('IN_SOLVEIT') and in_ipython() and bool(solveit_version())): return False
    try:
        if find_dname(): return True
    except: pass
    return False

# %% ../nbs/00_dutil.ipynb #a0c6cf33
def get_caller_globals(): 
    "Return the globals of the caller"
    return inspect.currentframe().f_back.f_globals

# %% ../nbs/00_dutil.ipynb #75ad25c7
async def ctxusage(id:str='', dname:str=''):
    msgs = await find_msgs(include_output=False, dname=dname)
    id = id or (await read_msg(0)).id
    pos = await msg_idx(id)
    return sum(m.input_tokens + (m.output_tokens or 0) for m in msgs[:pos] if not m.skipped)

# %% ../nbs/00_dutil.ipynb #e45e9175
# old version from `dialoghelper`, not thread safe
def _find_frame_dict(sentinel:str):
    "Find the globals dict containing sentinel, or calling frame's globals if no sentinel"
    frame = currentframe().f_back.f_back
    if not sentinel: return frame.f_globals
    while frame:
        if sentinel in frame.f_globals: return frame.f_globals
        frame = frame.f_back
    return globals()

def set_var(var:str, val, force:bool=False):
    "Set var to val after finding it in all frames of the call stack"
    frame = _find_frame_dict(var)
    if var not in frame and not force: raise ValueError(f"Could not find {var} in any scope")
    frame[var] = val

def find_var(var:str, default:Any=Parameter.empty):
    "Search for var in all frames of the call stack"
    if var in (frame := _find_frame_dict(var)): return frame[var]
    return default
find_var.notfound = Parameter.empty

# %% ../nbs/00_dutil.ipynb #3a1d4063
_ts, _te = ('<!-- ', '#| '), (' -->', '')
async def get_tag(name:str, val:str='', msg_type:str='note'):
    return f"{_ts[msg_type=='code']}{name}: {val or (await read_msg(0)).id}{_te[msg_type=='code']}"

# %% ../nbs/00_dutil.ipynb #bd2da5c6
_tagpats = {
    'code': (re.compile(r'\A#\|\W*(\w+): ([_a-f0-9]{9})\W*$', re.MULTILINE),
             re.compile(r'^#\|\W*(\w+): ([_a-f0-9]{9})\W*\Z', re.MULTILINE)),
    'note': (re.compile(r'\A<!-- (\w+): ([_a-f0-9]{9}) -->\W*$', re.MULTILINE),
             re.compile(r'^<!-- (\w+): ([_a-f0-9]{9}) -->\s*\Z', re.MULTILINE))
}
_tagpats['raw'] = _tagpats['prompt'] = _tagpats['note']
_tagpats[None] = _tagpats['note'] + _tagpats['code']

def has_tag(s:str, msg_type:str=None) -> bool:
    "Check if string contains tags created by get_tag at the start or end of the string"
    if msg_type == 'code' and not (s.startswith('#|') or '\n#|' in s): return False
    if msg_type == 'note' and not (s.startswith('<!--') or '\n<!--' in s): return False
    return any(re.search(pat, s) for pat in _tagpats[msg_type])

# %% ../nbs/00_dutil.ipynb #070879cc
def find_tag(s: str, msg_type: str = None) -> str:
    "Find tag in a string and return their details"
    for pat in _tagpats[msg_type]:
        if match := re.search(pat, s): return f"{match.group(1)}: {match.group(2)}"
    return ''

# %% ../nbs/00_dutil.ipynb #c8a25aeb
async def get_linked(id:str) -> str:
    if (msg := (await read_msg(0, id=id))).get('id','') == id:
        if tag := find_tag(msg.content, msg.msg_type):
            k,v = tag.split(': ')
            if k == 'linkedto': return v
    return ''

# %% ../nbs/00_dutil.ipynb #6b6c1b31
if in_dialog() and __name__ != '__main__': get_ipython().xpush(__linked_msgs={})

# %% ../nbs/00_dutil.ipynb #69fd0e09
delegates(add_msg)
async def link_msg(
    content:str=None,  # Content of the linked message
    id:str=None,  # ID of the message to link to, or current message if not provided
    pos:str='end',  # Position of the tag in the message
    **kwargs  # Additional keyword arguments for `add_msg` or `update_msg`
) -> str:  # id of linked message
    "Add or update a message linked to `anchor` message. Note only one linked msg per anchor."
    anchor_id, linked = id or (await read_msg(0)).id, find_var('__linked_msgs')
    def _with_tag(tag, c): return f"{tag}\n{c}" if pos=='start' else f"{c}\n{tag}"
    if linked_id := linked.get(anchor_id):
        if (msg := await read_msg(0, id=linked_id)).get('id','') == linked_id:
            tag = await get_tag('linkedto', anchor_id, kwargs.get('msg_type', msg.msg_type))
            if content: kwargs['content'] = _with_tag(tag, content)
            linked[anchor_id] = await update_msg(linked_id, **kwargs)
            return linked[anchor_id]
    tag = await get_tag('linkedto', anchor_id, kwargs.get('msg_type', 'note'))
    linked[anchor_id] = await add_msg(_with_tag(tag, content or '.'), id=anchor_id, **kwargs)  # NOTE: bug note message w/ only comment
    return linked[anchor_id]

# %% ../nbs/00_dutil.ipynb #dab704aa
async def hydrate():
    "Traverse dialog looking for linked messages to update `__linked_msgs`"
    linked = find_var('__linked_msgs')
    linked.clear()
    msgs = await find_msgs(include_meta=True, include_output=False, include_skipped=True)
    ids = {_.id for _ in msgs}
    for msg in msgs:
        if tag := find_tag(msg.get('content', ''), msg.get('msg_type')):
            k, v = tag.split(': ')
            if k == 'linkedto' and v in ids: linked[v] = msg['id']
    return linked

# %% ../nbs/00_dutil.ipynb #b9ae31c1
def waitpred(pred, timeout=0.5, interval=0.05):
    "Wait until `pred` is True or `timeout` is reached without blocking the kernel"
    async def _wait():
        start = time.time()
        while time.time()-start < timeout and not pred(): await sleep(interval)
        return pred()
    with start_blocking_portal() as portal: return portal.call(_wait)

# %% ../nbs/00_dutil.ipynb #c334d7b2
async def waitpreda(pred, timeout=0.5, interval=0.05):
    "Async wait until `pred` is True or `timeout` is reached without blocking the kernel"
    t0 = time.time()
    while not await pred():
        if time.time() - t0 > timeout: return False
        await sleep(0.1)
    return True

# %% ../nbs/00_dutil.ipynb #cc011438
def next_dup(fp, marker='_dup'):
    "Get next available duplicate number in fp parent directory"
    fp = Path(fp)
    p, nm, suff = fp.parent, fp.stem.split('.')[0], ''.join(fp.suffixes)
    nm = m[1] if (m := re.match(r'^(.+)'+re.escape(marker)+r'\d+$', nm)) else nm
    # if not p.exists(): i, p/f"{nm}{marker}{i}{suff}"
    dupr = re.compile(r'^'+re.escape(nm+marker)+r'(\d+)$')
    nums = sorted({int(m[1]) for f in p.iterdir() if (m := re.match(dupr, f.stem.split('.')[0]))})
    # if not nums: return 0, p/f"{nm}{suff}"
    for i,n in enumerate(nums, 1):
        if i != n: return i, p/f"{nm}{marker}{i}{suff}"
    return len(nums)+1, p/f"{nm}{marker}{len(nums)+1}{suff}"



# %% ../nbs/00_dutil.ipynb #9ec1c746
def next_filename(path:str):
    "Get next available duplicate filename for path, e.g., 'img.jpg' -> 'img_dup1.jpg'"
    _,fp = next_dup(Path(path))
    return str(fp)

# %% ../nbs/00_dutil.ipynb #a537ff31
def gen_id(): return f"_{uuid.uuid4().hex[:8]}"

# %% ../nbs/00_dutil.ipynb #5a3f523f
_empty = inspect.Parameter.empty

# %% ../nbs/00_dutil.ipynb #f300a22f
def at_(
    o, # Object to traverse (dict, list, object, or nested combination)
    sym: str, # Path using dots and/or brackets (e.g., 'a.b[0].c' or 'a[b][c]')",
    default: Any=_empty, # Value to return if path not found (raises exception if not provided)
    sep='.' # Separator for path segments
) -> Any: # Value at the specified path
    "Traverse nested `o` using path `sym` with dot notation and/or bracket indexing"
    sym = re.sub(r'\[([^\]]+)\]', r'.\1', sym)
    try:
        for a in filter(None, sym.split(sep)):
            if a.lstrip('-').isdigit(): a = int(a)
            try: o = o[a]
            except Exception:
                if isinstance(a, int):
                    try: o = o[str(a)]; continue
                    except Exception: pass
                o = getattr(o, a)
    except Exception:
        if default is not _empty: return default
        raise
    return o

# %% ../nbs/00_dutil.ipynb #60e5b6e0
async def setup_ns(ns=None, **kwargs):
    "Add `kwargs` to the namespace `ns` or current dialog"
    ns = ns or _find_frame_dict('__dialog_name')
    # lc = list(locals().items())[1:]
    thisid = (await read_msg(0)).id
    for k,v in kwargs.items(): ns[k] = v
    msgid = await link_msg('\n\n'.join(f"{k} = {v}" for k,v in kwargs.items()))
    print(thisid, msgid)

setup_dialog = setup_ns

# %% ../nbs/00_dutil.ipynb #fe59344e
def info(dname:str='', json:bool=False):
    "Returns information about the dialog"
    br, chngs, ver, dhv = (), (), solveit_version(), dialoghelper.__version__
    g = Git('.' if not dname else (Path.home()/find_dname(dname).lstrip('/')).parent) 
    if g.exists:
        br, *chngs = g('status', '-bs')
        br = br.split()[1].split('...')[0]
    return ({'Solveit': solveit_version(), 'dialoghelper': dialoghelper.__version__, 'git branch': br, 'git changes': chngs}
        if json else 
        f"Solveit: **v. {ver}**  \ndialoghelper: **v. {dhv}**  " + f"\ngit branch: **{br}**  \ngit changes: {chngs}" if br else '')

# %% ../nbs/00_dutil.ipynb #e2bc850b
async def add_info(msgid:str='', dname:str=''):
    "Add a message with information about the dialog"
    return await link_msg(info(dname), id=msgid)

# %% ../nbs/00_dutil.ipynb #8e88bb43
def summarize(target, context): pass

# %% ../nbs/00_dutil.ipynb #2f133f3b
def _get_ns(ns):
    if inspect.ismodule(ns): ns = vars(ns)
    elif isinstance(ns, str): ns = {k: get_ipython().user_ns[k] for _ in re.split(r'\s*,\s*', ns) if (k := _.strip())}
    return ns or get_ipython().user_ns

def get_tool_names(
    ns:Mapping|str=None,  # module,mapping,comma-separated str; None uses IPython user namespace
    exclude:Mapping|list[str]=None,  # module/mapping (recursively scanned) or list of symbol names to exclude
    only_exported:bool=False,  # if ns is a module, only include symbols in __all__
    exclude_private:bool=True  # exclude symbols starting with '_'
) -> dict[str,list[str]]:  # module name -> list of tool names
    "Return dict mapping module names to lists of usable tool names from namespace ns (or IPython user namespace if None)."
    ns = _get_ns(ns)
    if exclude: exclude = set(sum(get_tool_names(exclude).values(), []) if not is_listy(exclude) else exclude)
    res, vis, exports = defaultdict(list), defaultdict(set), set(ns.get('__all__', []))
    for k,v in ns.items():
        if exclude_private and k[0] == '_': continue
        if only_exported and k not in exports: continue
        if exclude and k in exclude: continue
        if not hasattr(__builtins__, k) and callable(v):
            try:
                if is_usable_tool(v): 
                    if inspect.isclass(v) and '__call__' not in v.__dict__: continue
                    if get_schema(v): 
                        mod = getattr(v, '__module__', 'unknown')
                        if v not in vis[mod]: res[mod].append(k); vis[mod].add(v)
            except Exception: pass
    return dict(res)

# %% ../nbs/00_dutil.ipynb #c7389abd
delegates(get_tool_names)
def show_tool_names(*args, **kwargs):
    for mn,syms in get_tool_names(*args, **kwargs).items():
        print(mn)
        print('  ', ', '.join(syms))

# %% ../nbs/00_dutil.ipynb #7fca2fc7
def mk_ns_toollist(ns, nms):
    ns = _get_ns(ns)
    return "\n".join(f"- &`{nm}`: {resolve_nm(nm, ns).__doc__}" for nm in nms)

# %% ../nbs/00_dutil.ipynb #e19bcfdf
delegates(get_tool_names)
async def add_tools_card(ns:Mapping|str=None, **kwargs):
    "Add a message with all tools in namespace `ns` or caller globals"
    ns = _get_ns(ns)
    mod2tool = get_tool_names(ns, **kwargs)
    content = '<!-- tool card -->\n\n' + '\n\n'.join(f"## {mod}\n\n{mk_ns_toollist(ns, tools)}" for mod,tools in mod2tool.items())
    await link_msg(content)
