"""fastgit patches and git utils"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_git.ipynb.

# %% auto #0
__all__ = ['dlg_diffs']

# %% ../nbs/02_git.ipynb #e72f67fd
from IPython.display import Markdown
import fastcore.all as FC
import nbdev
from nbdev.diff import cell_diffs
from nbdev.export import is_nbdev
from fastgit import Git, get_top
from dialoghelper.core import find_dname
from .dutil import nb_path, dlg_module

# %% ../nbs/02_git.ipynb #304b8e7c
_c_cmds = {'diff', 'log', 'status', 'show', 'blame', 'branch', 'reflog'}
_c_alias = {'cdiff', 'clog', 'cstatus', 'cshow', 'cblame', 'cbranch', 'creflog'}
_diffc = {'+': '\033[32m', '-': '\033[31m', '@': '\033[36m'}

def _cdiff(lines, nlines=100):
    for ln in lines[:nlines]: print(f"{_diffc.get(ln[0] if ln else '', '')}{ln}\033[0m")

def _cstatus(lines, nlines=100):
    for ln in lines[:nlines]:
        c = '\033[32m' if ln.startswith('\t') and 'new file' in ln else '\033[31m' if ln.startswith('\tmodified') or ln.startswith('\tdeleted') else '\033[36m' if ln.startswith('\t') else ''
        print(f"{c}{ln}\033[0m")

def _clog(lines, nlines=100):
    for ln in lines[:nlines]:
        c = '\033[33m' if ln.startswith('commit ') else '\033[32m' if ln.startswith('Author:') else '\033[36m' if ln.startswith('Date:') else ''
        print(f"{c}{ln}\033[0m")

def _creflog(lines, nlines=100):
    for ln in lines[:nlines]:
        parts = ln.split(' ', 1)
        print(f"\033[33m{parts[0]}\033[0m {parts[1] if len(parts)>1 else ''}")

_colorizers = dict(diff=_cdiff, show=_cdiff, status=_cstatus, log=_clog, blame=_clog, branch=_cstatus, reflog=_creflog)

# %% ../nbs/02_git.ipynb #11e21525
@FC.patch_to(Git, nm='__getattr__')
def _getattr(self, nm):
    if nm.startswith('_'): raise AttributeError(nm)
    is_c = nm in _c_alias
    if is_c: nm = nm[1:]
    cmd = nm.replace('_', '-')
    def _run(*args, color=None, nlines=100, **kwargs):
        res = self(cmd, *args, **kwargs)
        if res and (color or is_c): _colorizers.get(cmd, _cdiff)(res if isinstance(res, list) else res.splitlines(), nlines=nlines)
        else: return res
    return _run

# %% ../nbs/02_git.ipynb #7d5eb5f8
_fmt = '''
<details>
<summary>_%s</summary>

```diff
%s
```
</details>
'''

_nb_fmt = '''
<details>
<summary>%s</summary>

%s
</details>
'''
# _fmt = "_%s:\n\n```diff\n%s\n```"

# %% ../nbs/02_git.ipynb #c94c54db
def dlg_diffs(dname:str=''):
    dname = find_dname(dname)
    nb = nb_path(dname)
    g = Git(get_top(nb.parent))
    if not g.exists: return "Not a git repo"
    if is_nbdev():
        cfg_path = nbdev.config.get_config()
        mod = (cfg_path.lib_path/dlg_module(dname)).with_suffix('.py')
    else:
        mod = nb.with_suffix('.py')

    # f"_{id}:\n\n```diff\n{df}\n```"
    dfs = [_fmt % (id,df) for id,df in cell_diffs(nb).items()]
    # display(Markdown('\n---\n'.join(dfs)))
    nbs = _nb_fmt % (nb.relative_to(g.d), '\n'.join(dfs))

    if pdf := g.diff(str(mod)):
        display(Markdown(_nb_fmt % (mod.relative_to(g.d), pdf)))
    if nbs:
        display(Markdown(nbs))
    


dlg_diffs()
