# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_isolated.ipynb.

# %% auto #0
__all__ = ['isolate']

# %% ../nbs/02_isolated.ipynb #0abbc543
import json
import re
from pathlib import Path
from IPython.display import Markdown
from lisette import Chat
from fastcore.tools import create
import nbdev.config
from dialoghelper.core import curr_dialog, read_msg
from .dutil import next_filename, empty_dialog_nb

# %% ../nbs/02_isolated.ipynb #6c46c193
def _ask_llm(target_code: str) -> str:
    "Ask LLM to add minimal code before target code to make it run."
    chat_inst = Chat('claude-sonnet-4-5')
    resp = chat_inst(f'Add only the minimal code needed before this to make it run:\n```python\n{target_code}\n```')
    resp_text = resp.choices[0].message.content
    return resp_text

# %% ../nbs/02_isolated.ipynb #887d0c0b
def _get_deps(target_code: str) -> str:
    "Get dependencies of target code."
    resp_text = _ask_llm(target_code)
    prefix_code = re.search(r'```python\n(.*?)\n```', resp_text, re.DOTALL).group(1)
    idx = prefix_code.find(target_code)
    return prefix_code[:idx].strip() if idx != -1 else prefix_code

# %% ../nbs/02_isolated.ipynb #d770d842
def _get_nb(target_code: str, deps: str) -> dict:
    "Get notebook dict from target code and dependencies."
    nb = json.loads(empty_dialog_nb())
    d = {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': []}
    nb['cells'].extend([
        {**d, 'source': [f"{l}\n" for l in deps.splitlines()]},
        {**d, 'source': [f"{l}\n" for l in target_code.splitlines()]}
    ])
    return nb

# %% ../nbs/02_isolated.ipynb #6ca429fa
def _get_isolated_paths(staged:str='') -> list[str]:
    "Get list of path where isolated dialog will be saved and the url to access it."
    dpath = Path(curr_dialog()['name'])
    fn = dpath.stem
    staged = (Path(staged) if staged else dpath.parent)
    fp = (Path.home()/staged/fn).with_suffix('.ipynb')
    iso_fp = Path(next_filename(fp))
    iso_url = f"/dialog_?name={staged}/{iso_fp.stem}"
    return str(iso_fp), iso_url

# %% ../nbs/02_isolated.ipynb #ca7b4c1f
def _safe_isolated_paths(staged: str='', allow_nbs: bool=False) -> list[str]:
    "For nbdev project, get list of safe paths where isolated dialog will be saved and the url to access it."
    staged = Path(staged).resolve()
    if not allow_nbs and nbdev.config.is_nbdev() and 'nbs' in staged.parts:
        staged = nbdev.config.get_config().config_path/'explorer'
        staged.mkdir(exist_ok=True)
    staged = staged.relative_to(Path.home())
    return _get_isolated_paths(staged)

# %% ../nbs/02_isolated.ipynb #10eac77d
def _isolate_nb(ids=''):
    if not ids: ids = read_msg(n=-1, relative=True)['id']
    if isinstance(ids, str): ids = [i.strip() for i in ids.split(',')]
    target_codes = [read_msg(0, id=id)['content'] for id in ids]
    combined_code = '\n\n'.join(target_codes)
    deps = _get_deps(combined_code)
    return _get_nb(combined_code, deps)

# %% ../nbs/02_isolated.ipynb #c68e3759
def isolate(ids: str='', staged: str=''):
    "Create isolated dialog with target message(s) and auto-detected dependencies"
    nb = _isolate_nb(ids)
    iso_path, iso_url = _safe_isolated_paths(staged)
    res = create(iso_path, json.dumps(nb, indent=2))
    if 'Error' in res: return res
    return Markdown(f'<a href="{iso_url}" target="_blank">Open isolated dialog</a>')
