"""simple logger using idiomatic Solveit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_logger.ipynb.

# %% auto #0
__all__ = ['Logger', 'logger']

# %% ../nbs/02_logger.ipynb #38e6b396
import json
from datetime import datetime
from html import unescape
from fastcore.all import patch, delegates
from dialoghelper.core import update_msg, read_msg, curr_dialog
from anyio.from_thread import BlockingPortalProvider

# %% ../nbs/02_logger.ipynb #cc11f539
_provider = BlockingPortalProvider() # module level portal

# %% ../nbs/02_logger.ipynb #05ebc418
class Logger:
    "Timestamped logger that uses a cell's output as sink"
    async def setup(self, id:str='', dname:str='', clear:bool=False, prepend:bool=False): 
        curr = f"/{(await curr_dialog())['name']}"; self.dname = dname or curr
        self.msgid, self.prepend = id or (await read_msg(0)).id, prepend
        self._xs = self.dname != curr
        if clear: self._s = ''; return self.clear()
        self._s = unescape((await read_msg(0, id=self.msgid, dname=self.dname)).output) if dname else getattr(self, '_s', '')
    
    def clear(self): 
        self._s = '';
        with _provider as portal: portal.call(self._update, '')
    async def _update(self, output): await update_msg(self.msgid, output=output, dname=self.dname)

    @property
    def logs(self): return self._s.splitlines()
    async def show(self): self.msgid = (await read_msg(0)).id; print(self._s, end='')
    def __repr__(self): return self._s
    def __call__(self, *args, sep=' ', end='\n', file=None, flush=False): 
        dt = datetime.now()
        msg = sep.join(str(a) for a in args)
        s = f"[{dt:%H:%M:%S}.{dt.microsecond//1000:03d}] {msg}"
        self._s = (s + end + self._s) if self.prepend else (self._s + s + end)
        out = '[{"name": "stdout", "output_type": "stream", "text": %s}]' % json.dumps(self._s)
        with _provider as portal: portal.call(self._update, out)

@delegates(Logger.setup)
async def logger(**kwargs):
    "Logger factory"
    await (log := Logger()).setup(**kwargs)
    await log.show()
    return log

# %% ../nbs/02_logger.ipynb #8c9487aa
@patch
async def show(self:Logger, clear:bool=False):
    "Display log in current cell, optionally clearing first"
    if self._xs: self._s = unescape((await read_msg(0, id=self.msgid, dname=self.dname)).output)
    else:
        newid = (await read_msg(0)).id
        if self.msgid != newid:
            oldid = self.msgid
            await self.setup(newid)
            await update_msg(oldid, output='', dname=self.dname)
        if clear: self.clear()
    print(self._s, end='')
