# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_server.ipynb.

# %% auto #0
__all__ = ['daisyui_hdrs', 'threejs_hdrs', 'kill_port', 'is_serving', 'wrap_endp', 'find_server', 'get_preview', 'ensure_server',
           'stop_server', 'setup_uvi_logging', 'local_server']

# %% ../nbs/02_server.ipynb #92031bb1
import asyncio, logging, subprocess
from contextlib import asynccontextmanager
from datetime import datetime
from functools import partial
from fastcore.xml import FT
from fasthtml.core import FastHTML
from fasthtml.jupyter import JupyUvi, is_port_free, HTMX
from fasthtml.xtend import Script, Link
from dialoghelper.tmux import shell_ret
from .dutil import set_var

# %% ../nbs/02_server.ipynb #ff9bbe4e
def kill_port(port): subprocess.run(f"lsof -ti:{port} | xargs -r kill -9", shell=True)

# %% ../nbs/02_server.ipynb #fd28a288
def is_serving(srv, timeout=1):
    "Check if a JupyUvi instance is live and serving requests"
    if not (srv and srv.server and srv.server.started and not srv.server.should_exit and not is_port_free(srv.port)): return False
    try:
        import httpx
        return httpx.get(f"http://localhost:{srv.port}/", timeout=timeout).status_code < 500
    except Exception: return False

# %% ../nbs/02_server.ipynb #f3930f80
def wrap_endp(response):
    "If `response` is not callable, wrap a str/FT/sequence str|FT as a async endpoint"
    if callable(response) and not isinstance(response, FT) and not hasattr(response, '__ft__'): return response
    async def endpoint(request): return response
    return endpoint

# %% ../nbs/02_server.ipynb #48df1e1e
def find_server(port=8000):
    "Scan IPython user_ns for a JupyUvi instance on `port`"
    import IPython
    ns = IPython.get_ipython().user_ns
    for k,v in ns.items():
        if isinstance(v, JupyUvi) and v.port == port and v.server and v.server.started and not v.server.should_exit: return v,k
    return None, None

# %% ../nbs/02_server.ipynb #22fd909d
daisyui_hdrs = (
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
    Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'),
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5/themes.css', rel='stylesheet', type='text/css'),
)
threejs_hdrs = (
    Script('{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.165.0/examples/jsm/"}}', type='importmap'),
)

# %% ../nbs/02_server.ipynb #44f67a71
def get_preview(app): return partial(HTMX, app=app)

def ensure_server(srv=None, port=8000, hdrs=None):
    if not srv: srv,_ = find_server(port)
    if not srv:
        app = FastHTML(hdrs=hdrs or daisyui_hdrs)
        srv = JupyUvi(app)
    else: app = srv.app
    return app, app.route, srv, get_preview(app)

def stop_server(port=8000):
    srv, sym = find_server(port)
    if is_serving(srv):
        srv.stop()
        set_var(sym, None)

# %% ../nbs/02_server.ipynb #3e47ca82
def log(msg, *args, **kwargs): print(f"[{datetime.now():%H:%M:%S}] {msg}", flush=True)

# %% ../nbs/02_server.ipynb #d544286b
class LoggerHandler(logging.Handler):
    def __init__(self, log): self.log = log; super().__init__()
    def emit(self, record): self.log(f"{(record.levelname+':'):<10}{self.format(record)}")

# %% ../nbs/02_server.ipynb #9480d35b
def setup_uvi_logging(_log=None):
    _log = _log or log
    _lh = LoggerHandler(_log)
    for name in ('uvicorn', 'uvicorn.error', 'uvicorn.access'):
        lg = logging.getLogger(name)
        lg.handlers, lg.propagate = [_lh], False
        lg.setLevel(logging.DEBUG)

# %% ../nbs/02_server.ipynb #4759dac5
@asynccontextmanager
async def local_server(app=None, port=8000, after_start=None, before_stop=None, quiet=True, timeout=5, **jupyuvi_kw):
    "Yield a running JupyUvi server that can be used for testing; spins one up if needed, then cleanly tears it down afterwards"
    server = None
    if not is_port_free(port): 
        srv,_ = find_server(port)
        if srv is None: raise RuntimeError(f"Port {port} in use but no JupyUvi instance found in namespace")
        if not is_serving(srv): raise RuntimeError(f"Port {port} in use but JupyUvi server is not usable")
    else: 
        server = srv = JupyUvi(app or FastHTML(), port=port, start=False, **jupyuvi_kw)
        await srv.start_async()
        if not quiet:
            try: print(f">>> started: {srv.server.started}\n{shell_ret(f'lsof -i :{port}')}")
            except Exception as e: print(f">>> server startup failed: {e}")
    if after_start: await after_start(srv) if asyncio.iscoroutinefunction(after_start) else after_start(srv)
    try: yield srv
    finally:
        if before_stop: await before_stop(srv) if asyncio.iscoroutinefunction(before_stop) else before_stop(srv)
        if not server: return
        srv.server.should_exit = True
        deadline = (loop := asyncio.get_running_loop()).time() + timeout
        while not is_port_free(port):
            if loop.time() > deadline:
                print(f"WARNING: port {port} still in use after {timeout}s"); break
            await asyncio.sleep(0.1)
        if not quiet:
            try: print(f"<<< after stop: port {port} {'still in use' if shell_ret(f'lsof -i :{port}') else 'free'}")
            except Exception as e: print(f"<<< teardown failed: {e}")
