"""tree data structure helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tree.ipynb.

# %% auto #0
__all__ = ['is_tree', 'exclude', 'search', 'search_path', 'walk', 'filter_leaves', 'prune', 'TreeNode', 'TreeWalk', 'visit',
           'transform', 'rename', 'remove', 'clean', 'insert', 'update', 'move', 'reduce_leaves', 'show_path', 'pprint',
           'FileMeta']

# %% ../nbs/01_tree.ipynb #5c7f7c5b
from pathlib import Path
from typing import Mapping, Sequence, Hashable, Callable, Any
from operator import attrgetter

from fastcore.foundation import L, AttrDict, patch, noop
from fasthtml.components import Details, Summary, Ul, Li, show

from .basic import is_listy, val_atpath
from .callback import CBs, HasCallbacks

# %% ../nbs/01_tree.ipynb #daa41fab
# Pre 3.12+
# from typing import Any, TypeAlias
# Tree: TypeAlias = dict[str, list[Any | "Tree"]]

type Tree = Mapping[Hashable, Sequence[Any | Tree]]

# %% ../nbs/01_tree.ipynb #7f660a97
def search(m: Tree, pred: Callable):
    "Find all (path, leaf) pairs where leaf satisfies pred"
    return [(p, v) for p, v in walk(m) if pred(v)]

# %% ../nbs/01_tree.ipynb #63981195
def search_path(m: Tree, pred: Callable):
    "Find all (path, leaf) pairs where path satisfies pred"
    return [(p, v) for p, v in walk(m) if pred(p)]

# %% ../nbs/01_tree.ipynb #a0e3ce08
def walk(m: Tree, p: str=''):
    "Depth-first walk of a forest, yielding (path, leaf) pairs"
    for k, vs in m.items():
        cp = f"{p}.{k}" if p else k
        for i, item in enumerate(vs if is_listy(vs) else [vs]):
            if is_tree(item): yield from walk(item, f"{cp}.{i}")
            else: yield f"{cp}.{i}", item

# %% ../nbs/01_tree.ipynb #a50b7273
def filter_leaves(m: Tree, pred: Callable) -> Tree:
    "Keep only leaves satisfying pred, empty branches remain"
    return {k: [filter_leaves(v, pred) if is_tree(v) else v
                for v in (vs if is_listy(vs) else [vs]) if is_tree(v) or pred(v)]
            for k, vs in m.items()}

# %% ../nbs/01_tree.ipynb #1bc23529
def prune(m: Tree, pred: Callable) -> Tree:
    "Keep only leaves satisfying pred, removing empty branches"
    res = {}
    for k, vs in m.items():
        children = []
        for v in (vs if is_listy(vs) else [vs]):
            if is_tree(v):
                sub = prune(v, pred)
                if sub: children.append(sub)
            elif pred(v): children.append(v)
        if children: res[k] = children
    return res

# %% ../nbs/01_tree.ipynb #e28178a6
_SKIP = object()

# %% ../nbs/01_tree.ipynb #08eb8d8c
class TreeNode:
    "A named node with optional children and metadata"
    def __init__(self, key, children=None, **meta): self.key, self.children, self.meta = key, list(children or []), meta
    def __repr__(self): return f"TreeNode({self.key!r}, {self.children!r})" if not self.meta else f"TreeNode({self.key!r}, {self.children!r}, **{self.meta!r})"
    def __eq__(self, o): return isinstance(o, TreeNode) and self.key==o.key and self.children==o.children
    def is_leaf(self): return not self.children

is_tree = lambda o: isinstance(o, TreeNode)

# %% ../nbs/01_tree.ipynb #dbd302e5
_POST = object()

class TreeWalk(HasCallbacks):
    "Stack-based depth-first tree walker with callbacks"
    cbs_names = ('before_walk', 'after_walk', 'on_node_pre', 'on_node_post', 'on_leaf')

    def __init__(self, m: TreeNode, cbs=()):
        self.m = m
        super().__init__(cbs=cbs)

    def __iter__(self):
        self.callback('before_walk')
        stack = [((), self.m, 0, 0, 1, None)]
        while stack:
            p, v, depth, idx, n_sibs, tag = stack.pop()
            ctx = dict(depth=depth, idx=idx, n_sibs=n_sibs, is_last=idx==n_sibs-1)
            if tag is _POST: self.callback('on_node_post', p, v, ctx)
            elif is_tree(v):
                self.callback('on_node_pre', p, v, ctx)
                stack.append((p, v, depth, idx, n_sibs, _POST))
                n = len(v.children)
                for i, c in reversed(list(enumerate(v.children))):
                    cp = p + (c.key if is_tree(c) else i,)
                    stack.append((cp, c, depth+1, i, n, None))
                yield p, v, ctx
            else:
                self.callback('on_leaf', p, v, ctx)
                yield p, v, ctx
        self.callback('after_walk')

# %% ../nbs/01_tree.ipynb #ef6b4aa8
def visit(m: TreeNode, on_leaf: Callable=None, on_node_pre: Callable=None, on_node_post: Callable=None):
    "Depth-first walk calling callbacks for side effects"
    cbs = [CBs(**{k: v for k, v in dict(on_leaf=on_leaf, on_node_pre=on_node_pre, on_node_post=on_node_post).items() if v})]
    for _ in TreeWalk(m, cbs=cbs): pass

# %% ../nbs/01_tree.ipynb #de2e851e
def transform(m: TreeNode, on_leaf: Callable=None, on_node: Callable=None) -> TreeNode:
    "Depth-first structural transform, returning new TreeNode"
    if not is_tree(m): return on_leaf((), m) if on_leaf else m
    result_stack, current = [], []
    def _pre(ctx, p, v, c): result_stack.append(current.copy()); current.clear()
    def _post(ctx, p, v, c):
        children = list(current)
        node = on_node(p, TreeNode(v.key, children)) if on_node else TreeNode(v.key, children)
        current.clear(); current.extend(result_stack.pop())
        if node is not _SKIP: current.append(node)
    def _leaf(ctx, p, v, c):
        r = on_leaf(p, v) if on_leaf else v
        if r is not _SKIP: current.append(r)
    visit(m, on_leaf=_leaf, on_node_pre=_pre, on_node_post=_post)
    return current[0] if current else TreeNode(m.key)

# %% ../nbs/01_tree.ipynb #e2ff7a34
def rename(m: Tree, path, new_key):
    "Rename a node key in-place at path; raises if not found or new_key exists"
    *parent_path, old_key = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if old_key not in node: raise KeyError(f"{old_key!r} not found")
    if new_key in node: raise KeyError(f"{new_key!r} already exists")
    node[new_key] = node.pop(old_key)

# %% ../nbs/01_tree.ipynb #2b95f441
def remove(m: Tree, path):
    "Remove node or leaf at path in-place; raises if not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping): del node[last]
    elif is_listy(node): node.pop(int(last))
    else: raise KeyError(f"Cannot remove from {type(node)}")

# %% ../nbs/01_tree.ipynb #52ac1940
def clean(m: Tree):
    "Remove empty branches in-place recursively"
    for k in list(m):
        vs = m[k]
        if is_listy(vs):
            for v in vs:
                if is_tree(v): clean(v)
            m[k] = [v for v in vs if not ((is_tree(v) or is_listy(v)) and not v)]
            if not m[k]: del m[k]
        elif is_tree(vs) and not vs: del m[k]

# %% ../nbs/01_tree.ipynb #f80ffb73
def insert(m: Tree, path, value):
    "Insert value at path in-place; raises if already exists or parent not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping):
        if last in node: raise KeyError(f"{last!r} already exists")
        node[last] = value
    elif is_listy(node):
        try: node.insert(int(last), value)
        except ValueError: node.append({last: value})
    else: raise KeyError(f"Cannot insert into {type(node)}")

# %% ../nbs/01_tree.ipynb #2e7a8799
def update(m: Tree, path, value):
    "Update value at path in-place; raises if not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping):
        if last not in node: raise KeyError(f"{last!r} not found")
        node[last] = value
    elif is_listy(node): node[int(last)] = value
    else: raise KeyError(f"Cannot update {type(node)}")

# %% ../nbs/01_tree.ipynb #75542f0f
def move(m: Tree, src, dst):
    "Move node at src path to dst path in-place; raises if src not found or dst exists"
    *sp, sk = src if is_listy(src) else src.split('.')
    snode = val_atpath(m, *sp) if sp else m
    if isinstance(snode, Mapping):
        if sk not in snode: raise KeyError(f"{sk!r} not found")
        value = snode.pop(sk)
    elif is_listy(snode): value = snode.pop(int(sk))
    else: raise KeyError(f"Cannot move from {type(snode)}")
    insert(m, dst, value)

# %% ../nbs/01_tree.ipynb #b256040a
def reduce_leaves(m: Tree, f: Callable, init=None):
    "Reduce all leaves left-to-right with f(acc, val)"
    acc = init
    for _, v in walk(m): acc = f(acc, v)
    return acc

# %% ../nbs/01_tree.ipynb #f067f7da
exclude = ['.git', '__pycache__', '.ipynb_checkpoints']
_gett = attrgetter('name')

# %% ../nbs/01_tree.ipynb #99e0fe9b
@patch
def tree2(self:Path,
    file_type:str=None,
    file_exts:list=None,
    exclude:list=None,
    hidden:bool=False,
    max_level:int=None,
    on_file:Callable=None,
    on_dir:Callable=None,
) -> TreeNode:
    "Return a TreeNode rooted at path with optional inclusions/exclusions and leaf/node transforms"
    import mimetypes
    extns = L(file_exts)
    if file_type: extns += L(k for k,v in mimetypes.types_map.items() if v.startswith(file_type+'/'))
    has_extns, excl = len(extns)==0, set(exclude or [])
    def _kids(p, lvl=0):
        children = []
        for o in sorted(p.iterdir(), key=_gett):
            if o.name in excl or (not hidden and o.name.startswith('.')): continue
            if o.is_dir():
                at_limit = max_level is not None and lvl+1 >= max_level
                kids = [] if at_limit else _kids(o, lvl+1)
                children.append(on_dir(o, None if at_limit else kids) if on_dir else TreeNode(o, kids))
            elif has_extns or o.suffix in extns:
                children.append(on_file(o) if on_file else o)
        return children
    root = TreeNode(self, _kids(self))
    return on_dir(self, root.children) if on_dir else root

# %% ../nbs/01_tree.ipynb #70b3b27c
def _indent(indent=2):
    _pre = lambda p, v, ctx: print(' '*indent*ctx['depth'] + str(next(iter(v))) + ':')
    _leaf = lambda p, v, ctx: print(' '*indent*ctx['depth'] + str(v))
    # for k in tr: print(f"{k}:"); transform({k: tr[k]}, on_leaf=_leaf, on_node_pre=_pre)
    return dict(on_node_pre=_pre, on_leaf=_leaf)

# %% ../nbs/01_tree.ipynb #5bf73b3a
def _details_transform():
    def _leaf(p, v, ctx): return Li(v.name)
    def _node(p, v, ctx):
        wrp, nm = (Li, next(iter(v)).name) if p else (noop, next(iter(v)).resolve().name)
        return wrp(Details(Summary(nm), Ul(*next(iter(v.values()))), open=not bool(p)))
    return dict(on_leaf=_leaf, on_node=_node)

def show_path(path, exclude=None):
    tr = Path(path).tree(exclude=exclude)
    show(transform(tr, **_details_transform()))

# %% ../nbs/01_tree.ipynb #2ef0514e
def _print_indent(m, indent):
    visit(m,
        on_node_pre=lambda ctx, p, v, c: print(' '*indent*c['depth'] + str(v.key) + ':'),
        on_leaf=lambda ctx, p, v, c: print(' '*indent*c['depth'] + str(v)))

def _print_tree(m, color):
    _d,_r,_g = ('\033[34m','\033[0m','\033[38;5;7m') if color else ('','','')
    pres = []
    def _conn(c): return ''.join(pres) + (_g + ('└─ ' if c['is_last'] else '├─ ') + _r) * bool(c['depth'])
    def _pre(ctx, p, v, c):
        print(_conn(c) + _d + str(v.key) + _r)
        if c['depth']: pres.append('   ' if c['is_last'] else '│  ')
    def _post(ctx, p, v, c):
        if pres and c['depth']: pres.pop()
    visit(m, on_leaf=lambda ctx, p, v, c: print(_conn(c) + str(v)), on_node_pre=_pre, on_node_post=_post)

def pprint(m: TreeNode, style='indent', indent=2, color=True):
    "Pretty print a TreeNode in 'indent' or 'tree' style"
    if style == 'tree': _print_tree(m, color)
    else: _print_indent(m, indent)

# %% ../nbs/01_tree.ipynb #367ea335
class FileMeta(Path):
    "Path with attached metadata dict"
    def __new__(cls, *args, **kwargs): return super().__new__(cls, *args)
    def __init__(self, *args, **kwargs):
        super().__init__(*args)
        self.meta = AttrDict(kwargs)

# %% ../nbs/01_tree.ipynb #3553b404
@patch
def resolve(self:FileMeta, strict=False): return FileMeta(super().resolve(strict=strict), **self.meta)

@patch
def absolute(self:FileMeta): return FileMeta(super().absolute(), **self.meta)

@patch
def relative_to(self:FileMeta, *other): return FileMeta(super().relative_to(*other), **self.meta)
