"""tree data structure helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tree.ipynb.

# %% auto #0
__all__ = ['exclude', 'search', 'search_path', 'is_tree', 'filter_leaves', 'prune', 'walk', 'walk_s', 'rename', 'remove', 'clean',
           'insert', 'update', 'move', 'reduce_leaves', 'transform', 'map_leaves', 'map_nodes', 'pprint', 'show_path',
           'FileMeta']

# %% ../nbs/01_tree.ipynb #5c7f7c5b
from pathlib import Path
from typing import Mapping, Sequence, Hashable, Callable, Literal, Any
from operator import attrgetter

from fastcore.foundation import L, AttrDict, patch, noop
from fasthtml.components import Details, Summary, Ul, Li, show

from .basic import is_listy, val_atpath

# %% ../nbs/01_tree.ipynb #daa41fab
# Pre 3.12+
# from typing import Any, TypeAlias
# Tree: TypeAlias = dict[str, list[Any | "Tree"]]

type Tree = Mapping[Hashable, Sequence[Any | Tree]]

# %% ../nbs/01_tree.ipynb #7f660a97
def search(m: Tree, pred: Callable):
    "Find all (path, leaf) pairs where leaf satisfies pred"
    return [(p, v) for p, v in walk(m) if pred(v)]

# %% ../nbs/01_tree.ipynb #63981195
def search_path(m: Tree, pred: Callable):
    "Find all (path, leaf) pairs where path satisfies pred"
    return [(p, v) for p, v in walk(m) if pred(p)]

# %% ../nbs/01_tree.ipynb #a5489eab
def is_tree(o) -> bool: return isinstance(o, Mapping)

# %% ../nbs/01_tree.ipynb #a50b7273
def filter_leaves(m: Tree, pred: Callable) -> Tree:
    "Keep only leaves satisfying pred, empty branches remain"
    return {k: [filter_leaves(v, pred) if is_tree(v) else v
                for v in (vs if is_listy(vs) else [vs]) if is_tree(v) or pred(v)]
            for k, vs in m.items()}

# %% ../nbs/01_tree.ipynb #1bc23529
def prune(m: Tree, pred: Callable) -> Tree:
    "Keep only leaves satisfying pred, removing empty branches"
    res = {}
    for k, vs in m.items():
        children = []
        for v in (vs if is_listy(vs) else [vs]):
            if is_tree(v):
                sub = prune(v, pred)
                if sub: children.append(sub)
            elif pred(v): children.append(v)
        if children: res[k] = children
    return res

# %% ../nbs/01_tree.ipynb #670c538d
def walk(m: Tree, p: tuple=(), order: Literal['depth', 'breadth']='depth'):
    "Walk a forest yielding (path, leaf) pairs with tuple paths"
    if order == 'depth':
        for k, vs in m.items():
            cp = p + (k,)
            for i, v in enumerate(vs if is_listy(vs) else [vs]):
                if is_tree(v): yield from walk(v, cp + (i,), order)
                else: yield cp + (i,), v
    else:
        queue = [(p + (k,), vs) for k, vs in m.items()]
        while queue:
            cp, vs = queue.pop(0)
            for i, v in enumerate(vs if is_listy(vs) else [vs]):
                if is_tree(v): queue.extend([(cp + (i, k), vv) for k, vv in v.items()])
                else: yield cp + (i,), v

# %% ../nbs/01_tree.ipynb #4e4828f4
def walk_s(m: Tree, p: tuple=(), order: Literal['depth', 'breadth']='depth'):
    "Walk a forest using a stack/queue, yielding (path, leaf) pairs with tuple paths"
    init = [(p + (k,), v) for k, v in (reversed(list(m.items())) if order == 'depth' else m.items())]
    buf = list(init)
    while buf:
        cp, v = buf.pop() if order == 'depth' else buf.pop(0)
        if is_tree(v):
            items = reversed(list(v.items())) if order == 'depth' else v.items()
            for k, vv in items:
                vs = vv if is_listy(vv) else [vv]
                idxs = reversed(list(enumerate(vs))) if order == 'depth' else enumerate(vs)
                for i, item in idxs: buf.append((cp + (k, i), item))
        elif is_listy(v):
            idxs = reversed(list(enumerate(v))) if order == 'depth' else enumerate(v)
            for i, item in idxs: buf.append((cp + (i,), item))
        else: yield cp, v

# %% ../nbs/01_tree.ipynb #07130b58
def rename(m: Tree, path, new_key):
    "Rename a node key in-place at path; raises if not found or new_key exists"
    *parent_path, old_key = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if old_key not in node: raise KeyError(f"{old_key!r} not found")
    if new_key in node: raise KeyError(f"{new_key!r} already exists")
    node[new_key] = node.pop(old_key)

# %% ../nbs/01_tree.ipynb #da79df5b
def remove(m: Tree, path):
    "Remove node or leaf at path in-place; raises if not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping): del node[last]
    elif is_listy(node): node.pop(int(last))
    else: raise KeyError(f"Cannot remove from {type(node)}")

# %% ../nbs/01_tree.ipynb #89cb1c7a
def clean(m: Tree):
    "Remove empty branches in-place recursively"
    for k in list(m):
        vs = m[k]
        if is_listy(vs):
            for v in vs:
                if is_tree(v): clean(v)
            m[k] = [v for v in vs if not ((is_tree(v) or is_listy(v)) and not v)]
            if not m[k]: del m[k]
        elif is_tree(vs) and not vs: del m[k]

# %% ../nbs/01_tree.ipynb #cfeec220
def insert(m: Tree, path, value):
    "Insert value at path in-place; raises if already exists or parent not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping):
        if last in node: raise KeyError(f"{last!r} already exists")
        node[last] = value
    elif is_listy(node):
        try: node.insert(int(last), value)
        except ValueError: node.append({last: value})
    else: raise KeyError(f"Cannot insert into {type(node)}")

# %% ../nbs/01_tree.ipynb #6a6de250
def update(m: Tree, path, value):
    "Update value at path in-place; raises if not found"
    *parent_path, last = path if is_listy(path) else path.split('.')
    node = val_atpath(m, *parent_path) if parent_path else m
    if isinstance(node, Mapping):
        if last not in node: raise KeyError(f"{last!r} not found")
        node[last] = value
    elif is_listy(node): node[int(last)] = value
    else: raise KeyError(f"Cannot update {type(node)}")

# %% ../nbs/01_tree.ipynb #f411e375
def move(m: Tree, src, dst):
    "Move node at src path to dst path in-place; raises if src not found or dst exists"
    *sp, sk = src if is_listy(src) else src.split('.')
    snode = val_atpath(m, *sp) if sp else m
    if isinstance(snode, Mapping):
        if sk not in snode: raise KeyError(f"{sk!r} not found")
        value = snode.pop(sk)
    elif is_listy(snode): value = snode.pop(int(sk))
    else: raise KeyError(f"Cannot move from {type(snode)}")
    insert(m, dst, value)

# %% ../nbs/01_tree.ipynb #285960ba
def reduce_leaves(m: Tree, f: Callable, init=None):
    "Reduce all leaves left-to-right with f(acc, val)"
    acc = init
    for _, v in walk(m): acc = f(acc, v)
    return acc

# %% ../nbs/01_tree.ipynb #fbc134dc
exclude = ['.git', '__pycache__', '.ipynb_checkpoints']
_gett = attrgetter('name')

# %% ../nbs/01_tree.ipynb #fb915152
@patch
def tree(self:Path, 
    file_type:str=None,     # mime type to include, e.g. 'image'
    file_exts:list=None,    # file extensions to include, e.g. ['.py']
    exclude:list=None,      # names to exclude
    hidden:bool=False,      # include hidden files/dirs
    max_level:int=None,     # max depth to recurse; dirs at limit become unexpanded leaves
    on_file:Callable=None,  # replaces file leaf with return value; called with (path)
    on_dir:Callable=None,   # replaces dir node with return value; called with (path, children) or (path, None) for unexpanded dirs
) -> Tree:
    "Return a forest rooted at path with optional inclusions/exclusions and leaf/node transforms"
    import mimetypes
    extns=L(file_exts)
    if file_type: extns += L(k for k,v in mimetypes.types_map.items() if v.startswith(file_type+'/'))
    has_extns = len(extns)==0
    exclude = set(exclude or [])
    def _kids(p, lvl=0):
        if max_level is not None and lvl >= max_level: return []
        children = []
        for o in sorted(p.iterdir(), key=_gett):
            if o.name in exclude or (not hidden and o.name.startswith('.')): continue
            if o.is_dir():
                if max_level is not None and lvl+1 >= max_level: children.append(o if on_dir is None else on_dir(o, None))
                else: children.append({o: _kids(o, lvl+1)} if on_dir is None else on_dir(o, _kids(o, lvl+1)))
            elif has_extns or o.suffix in extns: children.append(on_file(o) if on_file else o)
        return children
    return {self: _kids(self)} if on_dir is None else on_dir(self, _kids(self))

# %% ../nbs/01_tree.ipynb #21aa4bcd
def transform(tr, on_leaf=None, on_node_pre=None, on_node=None, p=()):
    "Walk forest applying callbacks with context dict, returning new tree"
    res = {}
    for k, vs in tr.items():
        children, cp, wrapped = [], p + (k,), not is_listy(vs)
        vs = vs if not wrapped else [vs]
        n_ch = len(vs)
        for i, v in enumerate(vs):
            ip, ctx = cp + (i,), dict(idx=i, n_sibs=n_ch, is_last=i==n_ch-1, depth=len(cp))
            if is_tree(v):
                if on_node_pre: on_node_pre(ip, v, ctx)
                sv = transform(v, on_leaf, on_node_pre, on_node, ip)
                r = on_node(ip, sv, ctx) if on_node else None
                children.append(r if r is not None else sv)
            else:
                r = on_leaf(ip, v, ctx) if on_leaf else None
                children.append(r if r is not None else v)
        res[k] = children[0] if wrapped else children
    if on_node and res and not p:
        r = on_node(p, res, dict(depth=len(p), idx=0, n_sibs=1, is_last=True))
        if r is not None: res = r
    return res

# %% ../nbs/01_tree.ipynb #effdc057
def map_leaves(tr, f): return transform(tr, on_leaf=lambda p, v, ctx: f(v))
def map_nodes(tr, f): return transform(tr, on_node=lambda p, v, ctx: f(v))

# %% ../nbs/01_tree.ipynb #2c584bca
def _print_indent(tr, indent):
    _pre = lambda p, v, ctx: print(' '*indent*ctx['depth'] + str(next(iter(v))) + ':')
    _leaf = lambda p, v, ctx: print(' '*indent*ctx['depth'] + str(v))
    for k in tr: print(f"{k}:"); transform({k: tr[k]}, on_leaf=_leaf, on_node_pre=_pre)

def _print_tree(tr, color):
    _d,_r,_g = ('\033[34m','\033[0m','\033[38;5;7m') if color else ('','','')
    pres = []
    def _conn(ctx): return _g + ''.join(pres) + ('└─ ' if ctx['is_last'] else '├─ ') + _r
    def _leaf(p, v, ctx): print(_conn(ctx) + str(v))
    def _pre(p, v, ctx):
        print(_conn(ctx) + _d + str(next(iter(v))) + _r)
        pres.append('   ' if ctx['is_last'] else '│  ')
    def _post(p, v, ctx):
        if pres: pres.pop();
        return v
    for k, vs in tr.items():
        print(_d + str(k) + _r)
        pres.clear()
        transform({k: vs}, on_leaf=_leaf, on_node_pre=_pre, on_node=_post)
    
def pprint(tr, style='indent', indent=2, color=True):
    "Pretty print a forest in 'indent' or 'tree' style"
    if style == 'tree': _print_tree(tr, color)
    else: _print_indent(tr, indent)

# %% ../nbs/01_tree.ipynb #35c0c30a
def _details_transform():
    def _leaf(p, v, ctx): return Li(v.name)
    def _node(p, v, ctx):
        wrp, nm = (Li, next(iter(v)).name) if p else (noop, next(iter(v)).resolve().name)
        return wrp(Details(Summary(nm), Ul(*next(iter(v.values()))), open=not bool(p)))
    return dict(on_leaf=_leaf, on_node=_node)

def show_path(path, exclude=None):
    tr = Path(path).tree(exclude=exclude)
    show(transform(tr, **_details_transform()))

# %% ../nbs/01_tree.ipynb #367ea335
class FileMeta(Path):
    "Path with attached metadata dict"
    def __new__(cls, *args, **kwargs): return super().__new__(cls, *args)
    def __init__(self, *args, **kwargs):
        super().__init__(*args)
        self.meta = AttrDict(kwargs)

# %% ../nbs/01_tree.ipynb #3553b404
@patch
def resolve(self:FileMeta, strict=False): return FileMeta(super().resolve(strict=strict), **self.meta)

@patch
def absolute(self:FileMeta): return FileMeta(super().absolute(), **self.meta)

@patch
def relative_to(self:FileMeta, *other): return FileMeta(super().relative_to(*other), **self.meta)
