"""disclosure provides progressive discovery of code messages for AI consumption."""

# AUTOGENERATED! DO NOT EDIT! File to edit: code_disclosure_v1.ipynb.

import copy, re, json, ast, textwrap
from pathlib import Path
from dialoghelper.core import find_msgs

def _sig_src(node, src):
    "Get original source lines for just the signature (decorators thru colon)"
    ls = src.splitlines()
    start = node.decorator_list[0].lineno if node.decorator_list else node.lineno
    body_line = node.body[0].lineno - 1
    if start - 1 == body_line: return ls[start-1][:node.body[0].col_offset].rstrip()
    return '\n'.join(ls[start-1:body_line])

def _node_doc(node): return ast.get_docstring(node) or ''

def _param_comments(node, lines):
    "Get comments for each parameter from source lines"
    comments = {}
    for arg in node.args.args + node.args.posonlyargs + node.args.kwonlyargs:
        line = lines[arg.lineno - 1]
        if '#' in line: comments[arg.arg] = line.split('#', 1)[1].strip()
    return comments

_compound = (ast.If, ast.Try, ast.TryStar, ast.With, ast.For, ast.While)

def _subbodies(node):
    "Collect all child statement lists from a compound AST node"
    subs = []
    for attr in ('body', 'orelse', 'finalbody'): subs += getattr(node, attr, [])
    for h in getattr(node, 'handlers', []): subs += h.body
    return subs

def _stub(node, keep_doc=False):
    "Replace function/method bodies with `...`, recursing into class bodies"
    node = copy.deepcopy(node)
    if isinstance(node, ast.ClassDef):
        is_doc = lambda n: isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant) and isinstance(n.value.value, str)
        node.body = [_stub(n, keep_doc) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) else n
                     for n in node.body if keep_doc or not is_doc(n)]
    else:
        doc = [node.body[0]] if keep_doc and ast.get_docstring(node) else []
        node.body = doc + [ast.Expr(value=ast.Constant(value=...))]
    return node

def _compact(s): return re.sub(r'\n{2,}', '\n', s).strip()

def _fmt_doc(doc, ind):
    "Format docstring with `ind` indentation"
    if '\n' in doc: return f'{ind}"""{doc.replace(chr(10), chr(10)+ind)}"""'
    return f'{ind}"""{doc}"""' if '"' in doc else f'{ind}"{doc}"'

def _fmt_node(node, src, lines, level):
    "Format a single AST node at disclosure `level`"
    if level == 3:
        start = node.decorator_list[0].lineno-1 if node.decorator_list else node.lineno-1
        return '\n'.join(lines[start:node.end_lineno])
    if level == 1: return re.sub(r':\n +\.\.\.', ':...', ast.unparse(_stub(node)))
    sig = _sig_src(node, src)
    doc = _node_doc(node)
    one_liner = node.body[0].lineno == node.lineno
    ind = ' ' * (node.col_offset + 4 if one_liner else node.body[0].col_offset)
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return f'{sig}...' if not doc else f'{sig}\n{_fmt_doc(doc, ind)}\n{ind}...'
    hdr = f'{sig}\n{_fmt_doc(doc, ind)}' if doc else sig
    return '\n'.join(filter(None, [hdr] + _fmt_body(node.body, src, lines, level)))

def _fmt_compound(node, src, lines, level):
    "Format a compound AST node (if/try/with/for/while) at disclosure level"
    ind = '    ' * (node.col_offset // 4 + 1)
    def _indent(parts): return '\n'.join(ind + l for p in parts for l in textwrap.dedent(p).splitlines())
    if isinstance(node, ast.If):
        parts = [f'if {ast.unparse(node.test)}:', _indent(_fmt_body(node.body, src, lines, level))]
        if node.orelse: parts += ['else:', _indent(_fmt_body(node.orelse, src, lines, level))]
        return '\n'.join(filter(None, parts))
    return '\n'.join(_fmt_body(_subbodies(node), src, lines, level))

def _fmt_body(nodes, src, lines, level):
    "Format AST body nodes at disclosure level, returning list of source segments"
    parts = []
    for node in nodes:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            parts.append(_fmt_node(node, src, lines, level))
        elif isinstance(node, (ast.Assign, ast.AnnAssign, ast.TypeAlias)):
            seg = ast.get_source_segment(src, node)
            if seg: parts.append(' ' * node.col_offset + seg)
        elif isinstance(node, _compound):
            parts.append(_fmt_compound(node, src, lines, level))
    return parts

def disclose(src:str, level=1):
    "Return disclosure of `src` at `level` (1=sigs, 2=+docs/params, 3=full source)"
    tree, lines = ast.parse(src), src.splitlines()
    parts = []
    if tree.body and isinstance(tree.body[0], ast.Expr) and isinstance(tree.body[0].value, ast.Constant) and level > 1:
        parts.append(f'"""{tree.body[0].value.value}"""')
    if level > 1:
        imps = [ast.get_source_segment(src, n) for n in tree.body if isinstance(n, (ast.Import, ast.ImportFrom))]
        if imps: parts.append('\n'.join(imps))
    parts += _fmt_body(tree.body, src, lines, level)
    return _compact('\n\n'.join(filter(None, parts)))

def disclose_cell(src:str, level=1):
    "Disclose a single cell's source at `level`; returns original if not parseable Python"
    try: return disclose(src, level)
    except SyntaxError: return src

def _xml_cell(content, **attrs):
    attr_str = ''.join(f' {k}="{v}"' for k,v in attrs.items())
    return f'<cell{attr_str}>{content}</cell>'

async def disclose_dialog(dname:str='', level=1, only_exported=False, fmt='text'):
    "Return disclosed source of all code cells in dialog `dname` at `level`"
    msgs = await find_msgs(dname=dname, msg_type='code', include_output=False, only_exp=only_exported)
    parts = [(m['id'], disclose_cell(m['content'], level)) for m in msgs]
    parts = [(i,d) for i,d in parts if d]
    if fmt == 'xml':
        cells = '\n'.join(_xml_cell(d, id=i) for i,d in parts)
        return f'<dialog level="{level}" path="{dname or "."}">\n{cells}\n</dialog>'
    if fmt == 'json':
        return json.dumps(dict(level=level, path=dname or ".", cells=[dict(id=i, source=d) for i,d in parts]), indent=2)
    return _compact('\n\n'.join(d for _,d in parts))

def disclose_nb(path:str|Path, level=1, fmt='text'):
    "Return disclosed source of all code cells in notebook at `path` at `level`"
    nb = json.loads(Path(path).read_text())
    srcs = [c['source'] if isinstance(c['source'], str) else ''.join(c['source'])
            for c in nb['cells'] if c['cell_type'] == 'code']
    parts = [(i,d) for i,s in enumerate(srcs) if (d:=disclose_cell(s, level))]
    if fmt == 'xml':
        cells = '\n'.join(_xml_cell(d, id=i) for i,d in parts)
        return f'<nb level="{level}" path="{path}">\n{cells}\n</nb>'
    if fmt == 'json':
        return json.dumps(dict(level=level, path=str(path), cells=[dict(id=i, source=d) for i,d in parts]), indent=2)
    return _compact('\n\n'.join(d for _,d in parts))
