"""progressive discovery of code messages for AI consumption."""

# AUTOGENERATED! DO NOT EDIT! File to edit: code_disclosure_v2.ipynb.

import re, json, ast, warnings, copy, asttokens
from html import escape
from pathlib import Path
from fastcore.py2pyi import functypes

from pote.dialog import find_msgs_x, is_echo, is_exported

_exports = {'exporti', 'exports', 'export'}
_hidden = {'hide'}
_echo = {'echo', 'echo:'}

def _is_docstring(n): return isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant) and isinstance(n.value.value, str)

def _reindent(src, n): return '\n'.join(' '*n + l for l in src.splitlines())

def _postprocess(s):
    "Collapse triple+ blank lines and hoist lone `...` body onto the signature line"
    s = re.sub(r'\n{3,}', '\n\n', s)
    return re.sub(r':\n[ \t]+\.\.\.', ': ...', s)

_compound_types = (ast.If, ast.For, ast.While, ast.With, ast.Try, ast.Match)

def _strip_private(tree):
    "Remove private (underscore-prefixed) top-level nodes and class methods from `tree` in-place"
    is_priv = lambda n: getattr(n, 'name', '').startswith('_')
    tree.body = [n for n in tree.body if not is_priv(n)]
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            node.body = [n for n in node.body if not is_priv(n)]
    return tree

def stub_fn(atok, fn, level=1):
    "Return stubbed source for function `fn` at disclosure `level`"
    if level == 3: return atok.get_text(fn)
    start_line = fn.decorator_list[0].lineno if fn.decorator_list else fn.lineno
    body_start = fn.body[0].lineno - start_line
    if level == 1 or body_start == 0:
        n = copy.deepcopy(fn)
        n.body = [ast.Expr(ast.Constant(...))]
        return _reindent(ast.unparse(n), fn.col_offset)
    indent = ' ' * fn.body[0].col_offset
    lines = atok.get_text(fn).splitlines()
    if _is_docstring(fn.body[0]):
        doc_end = fn.body[0].end_lineno - start_line + 1
        return '\n'.join(lines[:body_start] + lines[body_start:doc_end] + [f'{indent}...'])
    return '\n'.join(lines[:body_start] + [f'{indent}...'])

def _class_chunk(atok, node, level):
    "Return disclosed source for class `node` at `level`"
    if level == 3: return atok.get_text(node)
    start_line = node.decorator_list[0].lineno if node.decorator_list else node.lineno
    body_start = node.body[0].lineno - start_line
    lines = atok.get_text(node).splitlines()
    hdr = '\n'.join(lines[:body_start])
    body = []
    for i,n in enumerate(node.body):
        if isinstance(n, functypes): body.append(stub_fn(atok, n, level))
        elif isinstance(n, ast.Expr):
            if i == 0 and _is_docstring(n) and level >= 2: body.append(' '*n.col_offset + atok.get_text(n))
        else: body.append(' '*n.col_offset + atok.get_text(n))
    return hdr + '\n' + '\n'.join(body)

def _compound_chunk(atok, node, level):
    "Return disclosed source for compound statement `node` at `level`"
    if level == 3: return atok.get_text(node)
    text = atok.get_text(node)
    fns = sorted([n for n in ast.walk(node) if n is not node and isinstance(n, (*functypes, ast.ClassDef))],
                 key=lambda n: (n.lineno, n.col_offset), reverse=True)
    for n in fns:
        stub = stub_fn(atok, n, level) if isinstance(n, functypes) else _class_chunk(atok, n, level)
        lines = stub.splitlines()
        if lines[0].startswith(' ' * n.col_offset): lines[0] = lines[0][n.col_offset:]
        text = text.replace(atok.get_text(n), '\n'.join(lines), 1)
    return text

def disclose(src:str, level=1, strip_private=False) -> str:
    "Disclose Python source at `level` (1=sigs, 2=sigs+docs, 3=full)"
    if not src.strip(): return ''
    try:
        atok = asttokens.ASTTokens(src, parse=True)
        if strip_private: _strip_private(atok.tree)
        chunks = []
        for i,node in enumerate(atok.tree.body):
            if isinstance(node, functypes): chunks.append(stub_fn(atok, node, level))
            elif isinstance(node, ast.ClassDef): chunks.append(_class_chunk(atok, node, level))
            elif isinstance(node, _compound_types): chunks.append(_compound_chunk(atok, node, level))
            elif isinstance(node, ast.Expr) and not (i == 0 and _is_docstring(node) and level >= 2): pass
            elif isinstance(node, (ast.Import, ast.ImportFrom)) and level == 1: pass
            else: chunks.append(atok.get_text(node))
        return _postprocess('\n\n'.join(chunks))
    except SyntaxError as e:
        warnings.warn(f'Syntax error in source, returning raw: {e}')
        return src

_include_filter = dict(
    exported=lambda m: is_exported(m),
    echo=lambda m: is_exported(m) or is_echo(m),
    all=lambda m: True)

def _compact(s): return re.sub(r'\n{2,}', '\n', s).strip()

def _xml_cell(content, **attrs):
    attr_str = ''.join(f' {k}="{v}"' for k,v in attrs.items())
    return f'<cell{attr_str}>{content}</cell>'

async def dialog_code(dname='', include='all'):
    "Return list of (id, source) tuples for code cells filtered by `include`"
    msgs = await find_msgs_x(dname=dname, msg_type='code', include_output=False)
    return [(m.id, m.content) for m in msgs if _include_filter[include](m)]

def _disclose_srcs(srcs, level=1, strip_private=False, fmt='text', dname=''):
    "Disclose list of (id, source) tuples at `level`"
    chunks = [(mid, disclose(src, level, strip_private)) for mid,src in srcs]
    if fmt == 'xml':
        cells = '\n'.join(_xml_cell(escape(src), id=mid) for mid,src in chunks)
        return f'<dialog level="{level}" path="{dname or "."}">\n{cells}\n</dialog>'
    if fmt == 'json':
        cells = [dict(id=mid, source=src) for mid,src in chunks]
        return json.dumps(dict(level=level, path=dname or '.', cells=cells), indent=2)
    return _compact('\n\n'.join(src for _,src in chunks))

async def disclose_dialog(dname='', level=1, include='all', strip_private=False, fmt='text'):
    "Disclose dialog `dname` at `level` filtering by `include`"
    srcs = await dialog_code(dname=dname, include=include)
    return _disclose_srcs(srcs, level=level, strip_private=strip_private, fmt=fmt, dname=dname)

def disclose_nb(path, level=1, strip_private=False, fmt='text'):
    "Return disclosed source of all code cells in notebook at `path`"
    nb = json.loads(Path(path).read_text())
    srcs = [(c.get('id',''), c['source'] if isinstance(c['source'], str) else ''.join(c['source']))
            for c in nb['cells'] if c['cell_type'] == 'code']
    return _disclose_srcs(srcs, level=level, strip_private=strip_private, fmt=fmt, dname=str(path))
